/*
 *
 *   Copyright 2026 soul_99 (suIMD)
 *
 *   Licensed under the GNU General Public License v3.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       https://www.gnu.org/licenses/gpl-3.0
 *
 *   GENERATED by design/_v3_rounded_star.py. Do not edit by hand; change the geometry there
 *   and re-run it. The header on that script is where the two knobs are explained.
 *
 */
package com.android.geto.designsystem.icon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/**
 * The app's star, rounded — the author's S1b.
 *
 * ⚠ **One geometry, drawn twice.** [GetoStarFilled] fills the path and [GetoStarHollow] strokes
 * a slightly smaller copy of it, so a favourite and a not-favourite are the same outline with and
 * without ink. Material's own Star/StarBorder pair is what these replace, and replacing both is
 * the point: a rounded star in the tab bar over pointy ones on every row reads as a mistake.
 *
 * ⚠ **Black, and that is not a colour decision.** `Icon` tints whatever it is handed, so the
 * colour here is only what the tint replaces. The same convention every Material icon uses.
 */
val GetoStarFilled: ImageVector by lazy {
    ImageVector.Builder(
        name = "GetoStarFilled",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).addPath(
        pathData = PathParser().parsePathString(FILLED_STAR_PATH).toNodes(),
        fill = SolidColor(Color.Black),
    ).build()
}

/**
 * The same star, hollow.
 *
 * Drawn on a smaller radius than the filled one so that half the stroke still lands inside the
 * 24-unit grid: an outline on the filled radius would have its outer edge clipped by any caller
 * that does not pad the icon, and `Icon` does not.
 */
val GetoStarHollow: ImageVector by lazy {
    ImageVector.Builder(
        name = "GetoStarHollow",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).addPath(
        pathData = PathParser().parsePathString(HOLLOW_STAR_PATH).toNodes(),
        stroke = SolidColor(Color.Black),
        strokeLineWidth = 1.6f,
        strokeLineCap = StrokeCap.Round,
        strokeLineJoin = StrokeJoin.Round,
    ).build()
}

private const val FILLED_STAR_PATH =
    "M10.630,4.074 A1.500,1.500 0 0 1 13.370,4.074 L14.769,7.212 A1.150,1.150 0 0 0 15.698,7.887 L19.115,8.248 A1.500,1.500 0 0 1 19.962,10.854 L17.410,13.154 A1.150,1.150 0 0 0 17.055,14.246 L17.767,17.607 A1.500,1.500 0 0 1 15.551,19.218 L12.575,17.501 A1.150,1.150 0 0 0 11.425,17.501 L8.449,19.218 A1.500,1.500 0 0 1 6.233,17.607 L6.945,14.246 A1.150,1.150 0 0 0 6.590,13.154 L4.038,10.854 A1.500,1.500 0 0 1 4.885,8.248 L8.302,7.887 A1.150,1.150 0 0 0 9.231,7.212 Z"

private const val HOLLOW_STAR_PATH =
    "M10.630,4.874 A1.500,1.500 0 0 1 13.370,4.874 L14.548,7.516 A1.150,1.150 0 0 0 15.477,8.191 L18.354,8.495 A1.500,1.500 0 0 1 19.201,11.101 L17.052,13.037 A1.150,1.150 0 0 0 16.697,14.130 L17.297,16.960 A1.500,1.500 0 0 1 15.080,18.571 L12.575,17.125 A1.150,1.150 0 0 0 11.425,17.125 L8.920,18.571 A1.500,1.500 0 0 1 6.703,16.960 L7.303,14.130 A1.150,1.150 0 0 0 6.948,13.037 L4.799,11.101 A1.500,1.500 0 0 1 5.646,8.495 L8.523,8.191 A1.150,1.150 0 0 0 9.452,7.516 Z"
