#!/usr/bin/env python3
"""One-off: every string the Auto-hide settings (IMD+) row, page and dialogs need.

feature/settings only. "IMD" and "IMD+" are product names and stay as they are in every locale.

The `auto_hide_info_hide_list` and `auto_hide_flow_3` lines are highlighted at runtime against
`settings_to_hide_title`, so each locale's sentence MUST contain that locale's own value of that
string verbatim. The check at the bottom asserts it rather than trusting it -- a mismatch is
silent at runtime, which is how the Russian highlighting bug got shipped.
"""
import os
import re
import sys

BASE = 'feature/settings/src/main/res'

L = ['values', 'values-ar', 'values-b+pt+BR', 'values-b+zh+Hans', 'values-de', 'values-es',
     'values-fr', 'values-hi', 'values-ja', 'values-ko', 'values-ru']

# Each locale's own "Settings to hide/ disable", so the two highlighted sentences can embed it.
HIDE_LIST = {
    'values': "Settings to hide/ disable",
    'values-ar': "الإعدادات المراد إخفاؤها / تعطيلها",
    'values-b+pt+BR': "Configurações a ocultar/ desativar",
    'values-b+zh+Hans': "要隐藏/停用的设置",
    'values-de': "Auszublendende / zu deaktivierende Einstellungen",
    'values-es': "Ajustes que se ocultan o desactivan",
    'values-fr': "Paramètres à masquer / désactiver",
    'values-hi': "छिपाई / बंद की जाने वाली सेटिंग्स",
    'values-ja': "非表示 / 無効にする設定",
    'values-ko': "숨기거나 끌 설정",
    'values-ru': "Скрываемые / отключаемые настройки",
}

NEW = {
    # ---- the row in the settings list ----
    'auto_hide': {
        'values': "Auto hide settings (IMD+ for advanced users only)",
        'values-ar': "‏إخفاء الإعدادات تلقائيًا (IMD+ للمستخدمين المتقدمين فقط)",
        'values-b+pt+BR': "Ocultar configurações automaticamente (IMD+ apenas para usuários avançados)",
        'values-b+zh+Hans': "自动隐藏设置（IMD+，仅限高级用户）",
        'values-de': "Einstellungen automatisch ausblenden (IMD+, nur für erfahrene Nutzer)",
        'values-es': "Ocultar ajustes automáticamente (IMD+, solo para usuarios avanzados)",
        'values-fr': "Masquage automatique des paramètres (IMD+, utilisateurs avancés uniquement)",
        'values-hi': "सेटिंग्स अपने आप छिपाएँ (IMD+ केवल उन्नत उपयोगकर्ताओं के लिए)",
        'values-ja': "設定を自動で非表示（IMD+、上級者向け）",
        'values-ko': "설정 자동 숨기기 (IMD+, 고급 사용자 전용)",
        'values-ru': "Автоскрытие настроек (IMD+, только для опытных пользователей)",
    },
    'auto_hide_setup': {
        'values': "Click to set up",
        'values-ar': "انقر للإعداد",
        'values-b+pt+BR': "Toque para configurar",
        'values-b+zh+Hans': "点按进行设置",
        'values-de': "Zum Einrichten tippen",
        'values-es': "Toca para configurar",
        'values-fr': "Appuyez pour configurer",
        'values-hi': "सेटअप के लिए टैप करें",
        'values-ja': "タップして設定",
        'values-ko': "눌러서 설정",
        'values-ru': "Нажмите, чтобы настроить",
    },
    'auto_hide_summary_blocked': {
        'values': "Paused — settings are hidden right now",
        'values-ar': "متوقف مؤقتًا — الإعدادات مخفية حاليًا",
        'values-b+pt+BR': "Em pausa — as configurações estão ocultas agora",
        'values-b+zh+Hans': "已暂停——设置目前处于隐藏状态",
        'values-de': "Pausiert — die Einstellungen sind gerade ausgeblendet",
        'values-es': "En pausa: los ajustes están ocultos ahora mismo",
        'values-fr': "En pause — les paramètres sont actuellement masqués",
        'values-hi': "रुका हुआ — सेटिंग्स अभी छिपी हुई हैं",
        'values-ja': "一時停止中 — 設定は現在非表示です",
        'values-ko': "일시 중지 — 설정이 지금 숨겨져 있습니다",
        'values-ru': "Приостановлено — настройки сейчас скрыты",
    },
    'auto_hide_summary_incomplete': {
        'values': "On, but something it needs is missing",
        'values-ar': "مُفعّل، لكن ينقصه شيء يحتاجه",
        'values-b+pt+BR': "Ativado, mas falta algo de que ele precisa",
        'values-b+zh+Hans': "已开启，但仍缺少所需的条件",
        'values-de': "Ein, aber etwas Benötigtes fehlt",
        'values-es': "Activado, pero falta algo que necesita",
        'values-fr': "Activé, mais il manque quelque chose",
        'values-hi': "चालू है, लेकिन ज़रूरी कुछ बाकी है",
        'values-ja': "オンですが、必要なものが足りません",
        'values-ko': "켜져 있지만 필요한 항목이 빠졌습니다",
        'values-ru': "Включено, но чего-то не хватает",
    },
    'auto_hide_summary_on': {
        'values': "On, watching %1$d app(s)",
        'values-ar': "‏مُفعّل، يراقب %1$d تطبيق/تطبيقات",
        'values-b+pt+BR': "Ativado, observando %1$d app(s)",
        'values-b+zh+Hans': "已开启，正在监视 %1$d 个应用",
        'values-de': "Ein, beobachtet %1$d App(s)",
        'values-es': "Activado, vigilando %1$d app(s)",
        'values-fr': "Activé, surveille %1$d application(s)",
        'values-hi': "चालू है, %1$d ऐप देखे जा रहे हैं",
        'values-ja': "オン、%1$d 個のアプリを監視中",
        'values-ko': "켜짐, %1$d개 앱 감시 중",
        'values-ru': "Включено, отслеживается приложений: %1$d",
    },

    # ---- the page ----
    'auto_hide_title': {
        'values': "Auto-hide settings (IMD+)",
        'values-ar': "‏إخفاء الإعدادات تلقائيًا (IMD+)",
        'values-b+pt+BR': "Ocultar configurações automaticamente (IMD+)",
        'values-b+zh+Hans': "自动隐藏设置（IMD+）",
        'values-de': "Einstellungen automatisch ausblenden (IMD+)",
        'values-es': "Ocultar ajustes automáticamente (IMD+)",
        'values-fr': "Masquage automatique des paramètres (IMD+)",
        'values-hi': "सेटिंग्स अपने आप छिपाएँ (IMD+)",
        'values-ja': "設定を自動で非表示（IMD+）",
        'values-ko': "설정 자동 숨기기 (IMD+)",
        'values-ru': "Автоскрытие настроек (IMD+)",
    },
    'auto_hide_description': {
        'values': "IMD+ hides your settings by itself when you open one of the apps you choose, then opens that app again so it starts with nothing to object to. Read “How IMD+ works” before switching it on — a run closes and reopens the app you tapped.",
        'values-ar': "‏يُخفي IMD+ إعداداتك من تلقاء نفسه عند فتح أحد التطبيقات التي تختارها، ثم يفتح ذلك التطبيق من جديد ليبدأ دون ما يعترض عليه. اقرأ «كيف يعمل IMD+» قبل تفعيله — فكل تشغيل يُغلق التطبيق الذي نقرت عليه ثم يفتحه مرة أخرى.",
        'values-b+pt+BR': "O IMD+ oculta as suas configurações sozinho quando você abre um dos apps escolhidos e, em seguida, abre esse app de novo para que ele comece sem nada a que possa se opor. Leia “Como o IMD+ funciona” antes de ativar — uma execução fecha e reabre o app que você tocou.",
        'values-b+zh+Hans': "当你打开所选应用之一时，IMD+ 会自行隐藏你的设置，然后重新打开该应用，使其启动时没有可反对的内容。开启前请先阅读“IMD+ 的工作方式”——每次运行都会关闭并重新打开你点按的应用。",
        'values-de': "IMD+ blendet deine Einstellungen von selbst aus, sobald du eine der gewählten Apps öffnest, und öffnet diese App danach erneut, damit sie ohne Beanstandungen startet. Lies vor dem Einschalten „So funktioniert IMD+“ — ein Durchlauf schließt die getippte App und öffnet sie wieder.",
        'values-es': "IMD+ oculta tus ajustes por su cuenta cuando abres una de las apps que elijas y después vuelve a abrir esa app para que arranque sin nada que objetar. Lee «Cómo funciona IMD+» antes de activarlo: una ejecución cierra y vuelve a abrir la app que has tocado.",
        'values-fr': "IMD+ masque vos paramètres de lui-même quand vous ouvrez une des applications choisies, puis rouvre cette application afin qu\\'elle démarre sans rien à redire. Lisez « Comment fonctionne IMD+ » avant de l\\'activer — une exécution ferme puis rouvre l\\'application touchée.",
        'values-hi': "जब आप अपने चुने हुए ऐप्स में से कोई खोलते हैं, तो IMD+ खुद ही आपकी सेटिंग्स छिपा देता है और फिर उस ऐप को दोबारा खोल देता है, ताकि वह बिना किसी आपत्ति के शुरू हो। चालू करने से पहले “IMD+ कैसे काम करता है” पढ़ें — हर बार वह आपके टैप किए ऐप को बंद करके फिर से खोलता है।",
        'values-ja': "選んだアプリのいずれかを開くと、IMD+ が自動で設定を非表示にし、そのアプリを開き直します。アプリは문句のない状態で起動します。オンにする前に「IMD+ の仕組み」をお読みください — 実行のたびにタップしたアプリを閉じて開き直します。",
        'values-ko': "선택한 앱 중 하나를 열면 IMD+가 알아서 설정을 숨긴 뒤 그 앱을 다시 엽니다. 그래서 앱은 트집 잡을 것이 없는 상태로 시작합니다. 켜기 전에 “IMD+ 작동 방식”을 읽어 보세요 — 실행할 때마다 누른 앱을 닫았다가 다시 엽니다.",
        'values-ru': "IMD+ сам скрывает ваши настройки, когда вы открываете одно из выбранных приложений, а затем открывает это приложение заново, чтобы оно запустилось без придирок. Перед включением прочитайте «Как работает IMD+» — при каждом запуске приложение, которое вы нажали, закрывается и открывается снова.",
    },
    'auto_hide_switch': {
        'values': "Auto-hide settings",
        'values-ar': "إخفاء الإعدادات تلقائيًا",
        'values-b+pt+BR': "Ocultar configurações automaticamente",
        'values-b+zh+Hans': "自动隐藏设置",
        'values-de': "Einstellungen automatisch ausblenden",
        'values-es': "Ocultar ajustes automáticamente",
        'values-fr': "Masquage automatique des paramètres",
        'values-hi': "सेटिंग्स अपने आप छिपाएँ",
        'values-ja': "設定を自動で非表示",
        'values-ko': "설정 자동 숨기기",
        'values-ru': "Автоскрытие настроек",
    },
    'auto_hide_switch_on': {
        'values': "On. IMD+ is watching the apps you chose.",
        'values-ar': "‏مُفعّل. يراقب IMD+ التطبيقات التي اخترتها.",
        'values-b+pt+BR': "Ativado. O IMD+ está observando os apps que você escolheu.",
        'values-b+zh+Hans': "已开启。IMD+ 正在监视你选定的应用。",
        'values-de': "Ein. IMD+ beobachtet die gewählten Apps.",
        'values-es': "Activado. IMD+ vigila las apps que has elegido.",
        'values-fr': "Activé. IMD+ surveille les applications choisies.",
        'values-hi': "चालू है। IMD+ आपके चुने हुए ऐप्स पर नज़र रख रहा है।",
        'values-ja': "オン。IMD+ が選んだアプリを監視しています。",
        'values-ko': "켜짐. IMD+가 선택한 앱을 감시하고 있습니다.",
        'values-ru': "Включено. IMD+ отслеживает выбранные приложения.",
    },
    'auto_hide_switch_off': {
        'values': "Off. Nothing happens when a watched app opens.",
        'values-ar': "مُعطّل. لا يحدث شيء عند فتح تطبيق مُراقَب.",
        'values-b+pt+BR': "Desativado. Nada acontece quando um app observado é aberto.",
        'values-b+zh+Hans': "已关闭。打开受监视的应用时不会发生任何事。",
        'values-de': "Aus. Beim Öffnen einer beobachteten App passiert nichts.",
        'values-es': "Desactivado. No ocurre nada al abrir una app vigilada.",
        'values-fr': "Désactivé. Rien ne se passe à l\\'ouverture d\\'une application surveillée.",
        'values-hi': "बंद है। देखे जा रहे ऐप के खुलने पर कुछ नहीं होता।",
        'values-ja': "オフ。監視対象のアプリを開いても何も起こりません。",
        'values-ko': "꺼짐. 감시 중인 앱을 열어도 아무 일도 일어나지 않습니다.",
        'values-ru': "Выключено. При открытии отслеживаемого приложения ничего не происходит.",
    },
    'auto_hide_switch_incomplete': {
        'values': "Cannot run yet — see the requirements below.",
        'values-ar': "لا يمكن التشغيل بعد — راجع المتطلبات أدناه.",
        'values-b+pt+BR': "Ainda não pode funcionar — veja os requisitos abaixo.",
        'values-b+zh+Hans': "尚无法运行——请查看下方的条件。",
        'values-de': "Kann noch nicht laufen — siehe die Voraussetzungen unten.",
        'values-es': "Todavía no puede funcionar: consulta los requisitos de abajo.",
        'values-fr': "Ne peut pas encore fonctionner — voyez les conditions ci-dessous.",
        'values-hi': "अभी चल नहीं सकता — नीचे दी गई ज़रूरतें देखें।",
        'values-ja': "まだ実行できません — 下の要件をご確認ください。",
        'values-ko': "아직 실행할 수 없습니다 — 아래 요건을 확인하세요.",
        'values-ru': "Пока не может работать — см. требования ниже.",
    },
    'auto_hide_switch_blocked': {
        'values': "Settings are hidden right now. Revert first, then switch IMD+ on.",
        'values-ar': "‏الإعدادات مخفية حاليًا. استعِدها أولًا ثم فعّل IMD+.",
        'values-b+pt+BR': "As configurações estão ocultas agora. Reverta primeiro e depois ative o IMD+.",
        'values-b+zh+Hans': "设置目前处于隐藏状态。请先还原，再开启 IMD+。",
        'values-de': "Die Einstellungen sind gerade ausgeblendet. Erst zurücksetzen, dann IMD+ einschalten.",
        'values-es': "Los ajustes están ocultos ahora mismo. Revierte primero y luego activa IMD+.",
        'values-fr': "Les paramètres sont actuellement masqués. Restaurez-les d\\'abord, puis activez IMD+.",
        'values-hi': "सेटिंग्स अभी छिपी हुई हैं। पहले वापस लाएँ, फिर IMD+ चालू करें।",
        'values-ja': "設定は現在非表示です。先に元に戻してから IMD+ をオンにしてください。",
        'values-ko': "설정이 지금 숨겨져 있습니다. 먼저 되돌린 뒤 IMD+를 켜세요.",
        'values-ru': "Настройки сейчас скрыты. Сначала верните их, затем включите IMD+.",
    },
    'auto_hide_how_it_works': {
        'values': "How IMD+ works",
        'values-ar': "‏كيف يعمل IMD+",
        'values-b+pt+BR': "Como o IMD+ funciona",
        'values-b+zh+Hans': "IMD+ 的工作方式",
        'values-de': "So funktioniert IMD+",
        'values-es': "Cómo funciona IMD+",
        'values-fr': "Comment fonctionne IMD+",
        'values-hi': "IMD+ कैसे काम करता है",
        'values-ja': "IMD+ の仕組み",
        'values-ko': "IMD+ 작동 방식",
        'values-ru': "Как работает IMD+",
    },
    'auto_hide_how_it_works_summary': {
        'values': "The steps of a run, and what the revert does",
        'values-ar': "خطوات التشغيل وما تفعله الاستعادة",
        'values-b+pt+BR': "As etapas de uma execução e o que a reversão faz",
        'values-b+zh+Hans': "一次运行的步骤，以及还原会做什么",
        'values-de': "Die Schritte eines Durchlaufs und was das Zurücksetzen tut",
        'values-es': "Los pasos de una ejecución y qué hace la reversión",
        'values-fr': "Les étapes d\\'une exécution et ce que fait la restauration",
        'values-hi': "एक बार चलने के चरण, और वापसी क्या करती है",
        'values-ja': "実行の手順と、元に戻す操作の内容",
        'values-ko': "실행 단계와 되돌리기가 하는 일",
        'values-ru': "Шаги запуска и что делает возврат",
    },
    'auto_hide_apps': {
        'values': "Apps to watch",
        'values-ar': "التطبيقات المراد مراقبتها",
        'values-b+pt+BR': "Apps a observar",
        'values-b+zh+Hans': "要监视的应用",
        'values-de': "Zu beobachtende Apps",
        'values-es': "Apps que vigilar",
        'values-fr': "Applications à surveiller",
        'values-hi': "देखे जाने वाले ऐप्स",
        'values-ja': "監視するアプリ",
        'values-ko': "감시할 앱",
        'values-ru': "Отслеживаемые приложения",
    },
    'auto_hide_apps_none': {
        'values': "No apps chosen yet",
        'values-ar': "لم يتم اختيار أي تطبيق بعد",
        'values-b+pt+BR': "Nenhum app escolhido ainda",
        'values-b+zh+Hans': "尚未选择应用",
        'values-de': "Noch keine Apps gewählt",
        'values-es': "Todavía no has elegido ninguna app",
        'values-fr': "Aucune application choisie pour l\\'instant",
        'values-hi': "अभी कोई ऐप नहीं चुना गया",
        'values-ja': "アプリがまだ選ばれていません",
        'values-ko': "아직 선택한 앱이 없습니다",
        'values-ru': "Приложения ещё не выбраны",
    },
    'auto_hide_apps_chosen': {
        'values': "%1$d chosen",
        'values-ar': "‏تم اختيار %1$d",
        'values-b+pt+BR': "%1$d escolhido(s)",
        'values-b+zh+Hans': "已选择 %1$d 个",
        'values-de': "%1$d gewählt",
        'values-es': "%1$d elegidas",
        'values-fr': "%1$d sélectionnée(s)",
        'values-hi': "%1$d चुने गए",
        'values-ja': "%1$d 個を選択中",
        'values-ko': "%1$d개 선택됨",
        'values-ru': "Выбрано: %1$d",
    },
    'auto_hide_apps_description': {
        'values': "IMD+ acts when one of these apps comes to the front. Nothing here changes your device; the list is read the next time one of them is opened.",
        'values-ar': "‏يتصرف IMD+ عندما يظهر أحد هذه التطبيقات في المقدمة. لا شيء هنا يغيّر جهازك؛ تُقرأ القائمة في المرة التالية التي يُفتح فيها أحدها.",
        'values-b+pt+BR': "O IMD+ age quando um destes apps vem para a frente. Nada aqui altera o seu aparelho; a lista é lida na próxima vez que um deles for aberto.",
        'values-b+zh+Hans': "当这些应用之一来到前台时，IMD+ 才会行动。这里的设置不会更改你的设备；下次打开其中之一时才会读取该列表。",
        'values-de': "IMD+ wird aktiv, sobald eine dieser Apps in den Vordergrund kommt. Hier ändert sich nichts an deinem Gerät; die Liste wird beim nächsten Öffnen einer davon gelesen.",
        'values-es': "IMD+ actúa cuando una de estas apps pasa a primer plano. Aquí no se cambia nada en tu dispositivo; la lista se lee la próxima vez que se abra alguna.",
        'values-fr': "IMD+ agit quand une de ces applications passe au premier plan. Rien ici ne modifie votre appareil ; la liste est lue à la prochaine ouverture de l\\'une d\\'elles.",
        'values-hi': "जब इनमें से कोई ऐप सामने आता है, तभी IMD+ काम करता है। यहाँ कुछ भी आपके डिवाइस को नहीं बदलता; यह सूची अगली बार किसी ऐप के खुलने पर पढ़ी जाती है।",
        'values-ja': "これらのアプリのいずれかが前面に来たときに IMD+ が動きます。ここでは端末は変更されません。リストは次にどれかが開かれたときに読み取られます。",
        'values-ko': "이 앱들 중 하나가 앞으로 나오면 IMD+가 동작합니다. 여기서는 기기가 바뀌지 않으며, 목록은 다음에 그중 하나를 열 때 읽힙니다.",
        'values-ru': "IMD+ действует, когда одно из этих приложений выходит на передний план. Здесь ничего не меняется на устройстве; список считывается при следующем открытии одного из них.",
    },
    'auto_hide_apps_search': {
        'values': "Search apps",
        'values-ar': "ابحث في التطبيقات",
        'values-b+pt+BR': "Pesquisar apps",
        'values-b+zh+Hans': "搜索应用",
        'values-de': "Apps suchen",
        'values-es': "Buscar apps",
        'values-fr': "Rechercher des applications",
        'values-hi': "ऐप्स खोजें",
        'values-ja': "アプリを検索",
        'values-ko': "앱 검색",
        'values-ru': "Поиск приложений",
    },
    'auto_hide_apps_loading': {
        'values': "Reading the installed apps…",
        'values-ar': "جارٍ قراءة التطبيقات المثبتة…",
        'values-b+pt+BR': "Lendo os apps instalados…",
        'values-b+zh+Hans': "正在读取已安装的应用…",
        'values-de': "Installierte Apps werden gelesen…",
        'values-es': "Leyendo las apps instaladas…",
        'values-fr': "Lecture des applications installées…",
        'values-hi': "इंस्टॉल किए गए ऐप्स पढ़े जा रहे हैं…",
        'values-ja': "インストール済みアプリを読み取っています…",
        'values-ko': "설치된 앱을 읽는 중…",
        'values-ru': "Чтение установленных приложений…",
    },
    'auto_hide_requirements': {
        'values': "Requirements",
        'values-ar': "المتطلبات",
        'values-b+pt+BR': "Requisitos",
        'values-b+zh+Hans': "所需条件",
        'values-de': "Voraussetzungen",
        'values-es': "Requisitos",
        'values-fr': "Conditions requises",
        'values-hi': "ज़रूरतें",
        'values-ja': "要件",
        'values-ko': "요건",
        'values-ru': "Требования",
    },
    'auto_hide_req_accessibility': {
        'values': "IMD+ accessibility service",
        'values-ar': "‏خدمة إمكانية الوصول الخاصة بـ IMD+",
        'values-b+pt+BR': "Serviço de acessibilidade do IMD+",
        'values-b+zh+Hans': "IMD+ 无障碍服务",
        'values-de': "IMD+ Bedienungshilfen-Dienst",
        'values-es': "Servicio de accesibilidad de IMD+",
        'values-fr': "Service d\\'accessibilité IMD+",
        'values-hi': "IMD+ एक्सेसिबिलिटी सेवा",
        'values-ja': "IMD+ のユーザー補助サービス",
        'values-ko': "IMD+ 접근성 서비스",
        'values-ru': "Служба специальных возможностей IMD+",
    },
    'auto_hide_req_accessibility_note': {
        'values': "How IMD notices that a watched app has opened. It reads only which app came to the front, never what is on your screen.",
        'values-ar': "‏بها يعرف IMD أن تطبيقًا مُراقَبًا قد فُتح. لا يقرأ سوى اسم التطبيق الذي ظهر في المقدمة، ولا يقرأ شيئًا مما على شاشتك.",
        'values-b+pt+BR': "É assim que o IMD percebe que um app observado foi aberto. Ele lê apenas qual app veio para a frente, nunca o que está na sua tela.",
        'values-b+zh+Hans': "IMD 借此得知受监视的应用已被打开。它只读取哪个应用来到前台，绝不读取屏幕上的内容。",
        'values-de': "Damit bemerkt IMD, dass eine beobachtete App geöffnet wurde. Es liest nur, welche App in den Vordergrund kam, niemals den Bildschirminhalt.",
        'values-es': "Así detecta IMD que se ha abierto una app vigilada. Solo lee qué app pasó a primer plano, nunca lo que hay en tu pantalla.",
        'values-fr': "C\\'est ainsi qu\\'IMD repère l\\'ouverture d\\'une application surveillée. Il lit uniquement quelle application est passée au premier plan, jamais le contenu de votre écran.",
        'values-hi': "इसी से IMD को पता चलता है कि कोई देखा जा रहा ऐप खुला है। यह सिर्फ़ यह पढ़ता है कि कौन-सा ऐप सामने आया, आपकी स्क्रीन का कुछ नहीं।",
        'values-ja': "監視対象のアプリが開かれたことを IMD が知る仕組みです。前面に来たアプリだけを読み取り、画面の内容は読み取りません。",
        'values-ko': "감시 중인 앱이 열렸음을 IMD가 아는 방법입니다. 어떤 앱이 앞으로 나왔는지만 읽으며 화면 내용은 읽지 않습니다.",
        'values-ru': "Так IMD узнаёт, что отслеживаемое приложение открылось. Считывается только то, какое приложение вышло на передний план, но не содержимое экрана.",
    },
    'auto_hide_req_shizuku_permission': {
        'values': "Shizuku permission",
        'values-ar': "‏إذن Shizuku",
        'values-b+pt+BR': "Permissão do Shizuku",
        'values-b+zh+Hans': "Shizuku 权限",
        'values-de': "Shizuku-Berechtigung",
        'values-es': "Permiso de Shizuku",
        'values-fr': "Autorisation Shizuku",
        'values-hi': "Shizuku अनुमति",
        'values-ja': "Shizuku の許可",
        'values-ko': "Shizuku 권한",
        'values-ru': "Разрешение Shizuku",
    },
    'auto_hide_req_shizuku_permission_note': {
        'values': "Needed to close a watched app. Tap to ask Shizuku for it.",
        'values-ar': "‏مطلوب لإغلاق تطبيق مُراقَب. انقر لطلبه من Shizuku.",
        'values-b+pt+BR': "Necessária para fechar um app observado. Toque para pedi-la ao Shizuku.",
        'values-b+zh+Hans': "关闭受监视的应用时需要。点按以向 Shizuku 申请。",
        'values-de': "Nötig, um eine beobachtete App zu schließen. Zum Anfragen bei Shizuku tippen.",
        'values-es': "Se necesita para cerrar una app vigilada. Toca para pedírselo a Shizuku.",
        'values-fr': "Nécessaire pour fermer une application surveillée. Appuyez pour la demander à Shizuku.",
        'values-hi': "देखे जा रहे ऐप को बंद करने के लिए ज़रूरी। Shizuku से माँगने के लिए टैप करें।",
        'values-ja': "監視対象のアプリを終了するために必要です。タップして Shizuku に要求します。",
        'values-ko': "감시 중인 앱을 닫는 데 필요합니다. 눌러서 Shizuku에 요청하세요.",
        'values-ru': "Нужно, чтобы закрыть отслеживаемое приложение. Нажмите, чтобы запросить его у Shizuku.",
    },
    'auto_hide_req_shizuku_configured': {
        'values': "Shizuku fork configured",
        'values-ar': "‏تهيئة نسخة Shizuku",
        'values-b+pt+BR': "Fork do Shizuku configurado",
        'values-b+zh+Hans': "已配置 Shizuku 分支",
        'values-de': "Shizuku-Fork eingerichtet",
        'values-es': "Fork de Shizuku configurado",
        'values-fr': "Fork Shizuku configuré",
        'values-hi': "Shizuku फ़ोर्क कॉन्फ़िगर किया गया",
        'values-ja': "Shizuku フォークの設定",
        'values-ko': "Shizuku 포크 설정됨",
        'values-ru': "Форк Shizuku настроен",
    },
    'auto_hide_req_shizuku_configured_note': {
        'values': "Filled in under the Shizuku section of these settings. Tap to go there.",
        'values-ar': "‏يُملأ ضمن قسم Shizuku في هذه الإعدادات. انقر للانتقال إليه.",
        'values-b+pt+BR': "Preenchido na seção Shizuku destas configurações. Toque para ir até lá.",
        'values-b+zh+Hans': "在本设置的 Shizuku 部分填写。点按前往。",
        'values-de': "Wird im Shizuku-Abschnitt dieser Einstellungen ausgefüllt. Zum Öffnen tippen.",
        'values-es': "Se rellena en la sección Shizuku de estos ajustes. Toca para ir allí.",
        'values-fr': "À renseigner dans la section Shizuku de ces paramètres. Appuyez pour y aller.",
        'values-hi': "इन्हीं सेटिंग्स के Shizuku भाग में भरा जाता है। वहाँ जाने के लिए टैप करें।",
        'values-ja': "この設定の Shizuku セクションで入力します。タップで移動します。",
        'values-ko': "이 설정의 Shizuku 섹션에서 입력합니다. 눌러서 이동하세요.",
        'values-ru': "Заполняется в разделе Shizuku этих настроек. Нажмите, чтобы перейти.",
    },
    'auto_hide_req_battery': {
        'values': "Battery use unrestricted",
        'values-ar': "استخدام البطارية غير مُقيَّد",
        'values-b+pt+BR': "Uso de bateria sem restrição",
        'values-b+zh+Hans': "电池使用不受限制",
        'values-de': "Akkunutzung nicht eingeschränkt",
        'values-es': "Uso de batería sin restricciones",
        'values-fr': "Utilisation de la batterie non restreinte",
        'values-hi': "बैटरी उपयोग अप्रतिबंधित",
        'values-ja': "電池使用の制限なし",
        'values-ko': "배터리 사용 제한 없음",
        'values-ru': "Работа в фоне без ограничений",
    },
    'auto_hide_req_battery_note': {
        'values': "A restricted IMD is frozen between runs and stops being told that an app has opened.",
        'values-ar': "‏عند تقييد IMD يُجمَّد بين عمليات التشغيل ويتوقف عن تلقّي الإشعار بأن تطبيقًا قد فُتح.",
        'values-b+pt+BR': "Um IMD restrito fica congelado entre execuções e deixa de ser avisado de que um app foi aberto.",
        'values-b+zh+Hans': "受限的 IMD 在两次运行之间会被冻结，不再被告知有应用被打开。",
        'values-de': "Ein eingeschränktes IMD wird zwischen den Durchläufen eingefroren und erfährt nicht mehr, dass eine App geöffnet wurde.",
        'values-es': "Un IMD restringido se congela entre ejecuciones y deja de recibir aviso de que se ha abierto una app.",
        'values-fr': "Un IMD restreint est gelé entre deux exécutions et n\\'est plus averti qu\\'une application vient de s\\'ouvrir.",
        'values-hi': "प्रतिबंधित IMD दो बार चलने के बीच जमा दिया जाता है और उसे यह बताया जाना बंद हो जाता है कि कोई ऐप खुला है।",
        'values-ja': "制限された IMD は実行の合間に凍結され、アプリが開かれたことを知らされなくなります。",
        'values-ko': "제한된 IMD는 실행 사이에 정지되어 앱이 열렸다는 사실을 더 이상 전달받지 못합니다.",
        'values-ru': "Ограниченный IMD замораживается между запусками и перестаёт получать сообщения об открытии приложения.",
    },
    'auto_hide_battery_settings': {
        'values': "Open battery settings",
        'values-ar': "افتح إعدادات البطارية",
        'values-b+pt+BR': "Abrir configurações de bateria",
        'values-b+zh+Hans': "打开电池设置",
        'values-de': "Akku-Einstellungen öffnen",
        'values-es': "Abrir ajustes de batería",
        'values-fr': "Ouvrir les paramètres de batterie",
        'values-hi': "बैटरी सेटिंग्स खोलें",
        'values-ja': "電池の設定を開く",
        'values-ko': "배터리 설정 열기",
        'values-ru': "Открыть настройки батареи",
    },
    'auto_hide_req_notifications': {
        'values': "Notifications allowed",
        'values-ar': "الإشعارات مسموح بها",
        'values-b+pt+BR': "Notificações permitidas",
        'values-b+zh+Hans': "已允许通知",
        'values-de': "Benachrichtigungen erlaubt",
        'values-es': "Notificaciones permitidas",
        'values-fr': "Notifications autorisées",
        'values-hi': "सूचनाएँ अनुमत",
        'values-ja': "通知が許可されている",
        'values-ko': "알림 허용됨",
        'values-ru': "Уведомления разрешены",
    },
    'auto_hide_req_notifications_note': {
        'values': "The IMD+ notification is the way back from a run.",
        'values-ar': "‏إشعار IMD+ هو طريق العودة بعد التشغيل.",
        'values-b+pt+BR': "A notificação do IMD+ é o caminho de volta depois de uma execução.",
        'values-b+zh+Hans': "IMD+ 的通知是运行之后的返回途径。",
        'values-de': "Die IMD+ Benachrichtigung ist der Weg zurück nach einem Durchlauf.",
        'values-es': "La notificación de IMD+ es el camino de vuelta tras una ejecución.",
        'values-fr': "La notification IMD+ est le chemin de retour après une exécution.",
        'values-hi': "एक बार चलने के बाद वापसी का रास्ता IMD+ की सूचना ही है।",
        'values-ja': "実行後に元へ戻る手段が IMD+ の通知です。",
        'values-ko': "실행 후 되돌아가는 길이 IMD+ 알림입니다.",
        'values-ru': "Уведомление IMD+ — это путь назад после запуска.",
    },
    'auto_hide_notification_settings': {
        'values': "Open notification settings",
        'values-ar': "افتح إعدادات الإشعارات",
        'values-b+pt+BR': "Abrir configurações de notificação",
        'values-b+zh+Hans': "打开通知设置",
        'values-de': "Benachrichtigungseinstellungen öffnen",
        'values-es': "Abrir ajustes de notificaciones",
        'values-fr': "Ouvrir les paramètres de notification",
        'values-hi': "सूचना सेटिंग्स खोलें",
        'values-ja': "通知の設定を開く",
        'values-ko': "알림 설정 열기",
        'values-ru': "Открыть настройки уведомлений",
    },
    'auto_hide_no_kill_launch': {
        'values': "Do not close the app on the first launch",
        'values-ar': "لا تُغلق التطبيق عند التشغيل الأول",
        'values-b+pt+BR': "Não fechar o app na primeira abertura",
        'values-b+zh+Hans': "首次启动时不要关闭该应用",
        'values-de': "Die App beim ersten Start nicht schließen",
        'values-es': "No cerrar la app en el primer arranque",
        'values-fr': "Ne pas fermer l\\'application au premier lancement",
        'values-hi': "पहली बार खुलने पर ऐप बंद न करें",
        'values-ja': "最初の起動でアプリを終了しない",
        'values-ko': "첫 실행에서 앱을 닫지 않기",
        'values-ru': "Не закрывать приложение при первом запуске",
    },
    'auto_hide_no_kill_launch_note': {
        'values': "IMD+ hides your settings and leaves the app alone. It has already read them, so it will only notice next time it starts.",
        'values-ar': "‏يُخفي IMD+ إعداداتك ويترك التطبيق كما هو. لقد قرأها بالفعل، فلن يلاحظ ذلك إلا عند تشغيله في المرة التالية.",
        'values-b+pt+BR': "O IMD+ oculta as suas configurações e deixa o app em paz. Ele já as leu, então só vai perceber na próxima vez que iniciar.",
        'values-b+zh+Hans': "IMD+ 只隐藏你的设置而不动该应用。它已经读取过了，因此只有下次启动时才会察觉。",
        'values-de': "IMD+ blendet deine Einstellungen aus und lässt die App in Ruhe. Sie hat sie bereits gelesen und merkt es erst beim nächsten Start.",
        'values-es': "IMD+ oculta tus ajustes y deja la app en paz. Ya los ha leído, así que solo lo notará la próxima vez que arranque.",
        'values-fr': "IMD+ masque vos paramètres et laisse l\\'application tranquille. Elle les a déjà lus et ne s\\'en apercevra qu\\'au prochain démarrage.",
        'values-hi': "IMD+ आपकी सेटिंग्स छिपा देता है और ऐप को नहीं छेड़ता। वह उन्हें पहले ही पढ़ चुका है, इसलिए अगली बार शुरू होने पर ही उसे पता चलेगा।",
        'values-ja': "IMD+ は設定を非表示にするだけで、アプリには手を触れません。アプリはすでに読み取り済みなので、気づくのは次回の起動時です。",
        'values-ko': "IMD+는 설정만 숨기고 앱은 건드리지 않습니다. 앱은 이미 설정을 읽었으므로 다음에 시작할 때에야 알아차립니다.",
        'values-ru': "IMD+ скрывает настройки и не трогает приложение. Оно уже их прочитало, поэтому заметит только при следующем запуске.",
    },
    'auto_hide_info_pending': {
        'values': "IMD+ will not start while any revert is still owed — from an app launched inside IMD, from an IMD shortcut, or from the tile. Finish the pending reverts first.",
        'values-ar': "‏لن يبدأ IMD+ ما دامت هناك استعادة مستحقة — من تطبيق فُتح داخل IMD، أو من اختصار أنشأه IMD، أو من المربّع. أكمل الاستعادات المعلّقة أولًا.",
        'values-b+pt+BR': "O IMD+ não vai iniciar enquanto houver alguma reversão pendente — de um app aberto dentro do IMD, de um atalho do IMD ou do bloco. Conclua as reversões pendentes primeiro.",
        'values-b+zh+Hans': "只要还有未完成的还原，IMD+ 就不会启动——无论来自在 IMD 内打开的应用、IMD 创建的快捷方式，还是磁贴。请先完成待处理的还原。",
        'values-de': "IMD+ startet nicht, solange noch ein Zurücksetzen aussteht — von einer in IMD geöffneten App, von einer IMD-Verknüpfung oder von der Kachel. Erledige zuerst die ausstehenden Rücksetzungen.",
        'values-es': "IMD+ no se pondrá en marcha mientras quede alguna reversión pendiente: de una app abierta dentro de IMD, de un acceso directo de IMD o del mosaico. Termina antes las reversiones pendientes.",
        'values-fr': "IMD+ ne démarrera pas tant qu\\'une restauration reste due — depuis une application ouverte dans IMD, depuis un raccourci IMD ou depuis la tuile. Terminez d\\'abord les restaurations en attente.",
        'values-hi': "जब तक कोई वापसी बाकी है, IMD+ शुरू नहीं होगा — चाहे वह IMD के भीतर खोले गए ऐप से हो, IMD के बनाए शॉर्टकट से, या टाइल से। पहले बकाया वापसियाँ पूरी करें।",
        'values-ja': "元に戻す操作が残っている間、IMD+ は動きません — IMD 内で開いたアプリ、IMD が作ったショートカット、タイルのいずれからのものでも同じです。先に保留中の復元を終わらせてください。",
        'values-ko': "되돌릴 것이 남아 있는 동안에는 IMD+가 시작되지 않습니다 — IMD 안에서 연 앱, IMD가 만든 바로가기, 타일 중 어느 것이든 마찬가지입니다. 먼저 대기 중인 되돌리기를 마치세요.",
        'values-ru': "IMD+ не запустится, пока остаётся невыполненный возврат — от приложения, открытого внутри IMD, от ярлыка IMD или от плитки. Сначала завершите отложенные возвраты.",
    },
    'auto_hide_info_deaf': {
        'values': "While settings are hidden, IMD+ is deliberately switched off — including its own accessibility service. The way back is its notification, the Hide settings tile, or a shortcut.",
        'values-ar': "‏أثناء إخفاء الإعدادات، يُعطَّل IMD+ عن قصد — بما في ذلك خدمة إمكانية الوصول الخاصة به. طريق العودة هو إشعاره، أو مربّع «إخفاء الإعدادات»، أو اختصار.",
        'values-b+pt+BR': "Enquanto as configurações estão ocultas, o IMD+ fica desligado de propósito — inclusive o seu próprio serviço de acessibilidade. O caminho de volta é a notificação dele, o bloco Ocultar configurações ou um atalho.",
        'values-b+zh+Hans': "在设置处于隐藏状态期间，IMD+ 会被有意关闭——包括它自己的无障碍服务。返回途径是它的通知、“隐藏设置”磁贴或快捷方式。",
        'values-de': "Solange die Einstellungen ausgeblendet sind, ist IMD+ absichtlich abgeschaltet — auch sein eigener Bedienungshilfen-Dienst. Zurück geht es über seine Benachrichtigung, die Kachel „Einstellungen ausblenden“ oder eine Verknüpfung.",
        'values-es': "Mientras los ajustes están ocultos, IMD+ queda apagado a propósito, incluido su propio servicio de accesibilidad. La vuelta se hace desde su notificación, el mosaico Ocultar ajustes o un acceso directo.",
        'values-fr': "Tant que les paramètres sont masqués, IMD+ est volontairement désactivé — y compris son propre service d\\'accessibilité. Le retour se fait par sa notification, la tuile Masquer les paramètres ou un raccourci.",
        'values-hi': "जब तक सेटिंग्स छिपी हैं, IMD+ जान-बूझकर बंद रहता है — उसकी अपनी एक्सेसिबिलिटी सेवा समेत। वापसी का रास्ता उसकी सूचना, “सेटिंग्स छिपाएँ” टाइल, या कोई शॉर्टकट है।",
        'values-ja': "設定が非表示の間、IMD+ は自らのユーザー補助サービスも含めて意図的にオフになります。戻る手段は、その通知、「設定を非表示」タイル、またはショートカットです。",
        'values-ko': "설정이 숨겨져 있는 동안 IMD+는 자체 접근성 서비스까지 포함해 의도적으로 꺼집니다. 되돌아가는 방법은 알림, ‘설정 숨기기’ 타일, 또는 바로가기입니다.",
        'values-ru': "Пока настройки скрыты, IMD+ намеренно выключен — вместе со своей службой специальных возможностей. Вернуться можно через его уведомление, плитку «Скрыть настройки» или ярлык.",
    },
    'auto_hide_info_hide_list': {
        'values': "IMD+ hides whatever is ticked in Settings to hide/ disable. It has no separate list of its own.",
        'values-ar': "‏يُخفي IMD+ ما هو محدَّد في الإعدادات المراد إخفاؤها / تعطيلها. ليس له قائمة منفصلة خاصة به.",
        'values-b+pt+BR': "O IMD+ oculta o que estiver marcado em Configurações a ocultar/ desativar. Ele não tem uma lista separada.",
        'values-b+zh+Hans': "IMD+ 隐藏的是在要隐藏/停用的设置中勾选的项目。它没有自己单独的列表。",
        'values-de': "IMD+ blendet aus, was unter Auszublendende / zu deaktivierende Einstellungen angehakt ist. Eine eigene Liste hat es nicht.",
        'values-es': "IMD+ oculta lo que esté marcado en Ajustes que se ocultan o desactivan. No tiene una lista propia aparte.",
        'values-fr': "IMD+ masque ce qui est coché dans Paramètres à masquer / désactiver. Il n\\'a pas de liste distincte.",
        'values-hi': "IMD+ वही छिपाता है जो छिपाई / बंद की जाने वाली सेटिंग्स में चुना गया है। उसकी अपनी अलग सूची नहीं है।",
        'values-ja': "IMD+ が隠すのは、非表示 / 無効にする設定でチェックした項目です。独自の一覧は持ちません。",
        'values-ko': "IMD+는 숨기거나 끌 설정에서 선택한 항목을 숨깁니다. 별도의 목록은 없습니다.",
        'values-ru': "IMD+ скрывает то, что отмечено в разделе Скрываемые / отключаемые настройки. Собственного отдельного списка у него нет.",
    },
    'auto_hide_info_battery': {
        'values': "Some manufacturers restrict apps again after a few days. If IMD+ stops noticing launches, this is the first thing to check.",
        'values-ar': "‏تعيد بعض الشركات المصنّعة تقييد التطبيقات بعد بضعة أيام. إذا توقف IMD+ عن ملاحظة عمليات الفتح، فهذا أول ما ينبغي التحقق منه.",
        'values-b+pt+BR': "Alguns fabricantes voltam a restringir os apps depois de alguns dias. Se o IMD+ parar de perceber as aberturas, verifique isto primeiro.",
        'values-b+zh+Hans': "有些厂商会在几天后重新限制应用。如果 IMD+ 不再察觉应用启动，这是首先要检查的地方。",
        'values-de': "Manche Hersteller schränken Apps nach ein paar Tagen wieder ein. Wenn IMD+ Starts nicht mehr bemerkt, ist das der erste Punkt zum Prüfen.",
        'values-es': "Algunos fabricantes vuelven a restringir las apps a los pocos días. Si IMD+ deja de detectar aperturas, esto es lo primero que hay que mirar.",
        'values-fr': "Certains fabricants restreignent de nouveau les applications au bout de quelques jours. Si IMD+ cesse de repérer les ouvertures, vérifiez d\\'abord ceci.",
        'values-hi': "कुछ निर्माता कुछ दिनों बाद ऐप्स को फिर से प्रतिबंधित कर देते हैं। अगर IMD+ ऐप खुलने को पकड़ना बंद कर दे, तो सबसे पहले यही देखें।",
        'values-ja': "メーカーによっては数日後にアプリを再び制限します。IMD+ が起動を検知しなくなったら、まずここを確認してください。",
        'values-ko': "일부 제조사는 며칠 뒤 앱을 다시 제한합니다. IMD+가 실행을 감지하지 못하게 되면 이곳을 가장 먼저 확인하세요.",
        'values-ru': "Некоторые производители снова ограничивают приложения через несколько дней. Если IMD+ перестал замечать запуски, проверьте это в первую очередь.",
    },

    # ---- the flow popup ----
    'auto_hide_flow_intro': {
        'values': "What happens when you open one of the apps you chose:",
        'values-ar': "ما يحدث عند فتح أحد التطبيقات التي اخترتها:",
        'values-b+pt+BR': "O que acontece quando você abre um dos apps escolhidos:",
        'values-b+zh+Hans': "当你打开所选应用之一时会发生什么：",
        'values-de': "Was passiert, wenn du eine der gewählten Apps öffnest:",
        'values-es': "Qué ocurre cuando abres una de las apps que has elegido:",
        'values-fr': "Ce qui se passe quand vous ouvrez une des applications choisies :",
        'values-hi': "जब आप अपने चुने हुए ऐप्स में से कोई खोलते हैं तो क्या होता है:",
        'values-ja': "選んだアプリのいずれかを開いたときの流れ:",
        'values-ko': "선택한 앱 중 하나를 열면 일어나는 일:",
        'values-ru': "Что происходит, когда вы открываете одно из выбранных приложений:",
    },
    'auto_hide_flow_1': {
        'values': "You open a watched app.",
        'values-ar': "تفتح تطبيقًا مُراقَبًا.",
        'values-b+pt+BR': "Você abre um app observado.",
        'values-b+zh+Hans': "你打开一个受监视的应用。",
        'values-de': "Du öffnest eine beobachtete App.",
        'values-es': "Abres una app vigilada.",
        'values-fr': "Vous ouvrez une application surveillée.",
        'values-hi': "आप कोई देखा जा रहा ऐप खोलते हैं।",
        'values-ja': "監視対象のアプリを開きます。",
        'values-ko': "감시 중인 앱을 엽니다.",
        'values-ru': "Вы открываете отслеживаемое приложение.",
    },
    'auto_hide_flow_2': {
        'values': "IMD+ closes it through Shizuku, before it has read anything.",
        'values-ar': "‏يُغلقه IMD+ عبر Shizuku قبل أن يقرأ أي شيء.",
        'values-b+pt+BR': "O IMD+ o fecha pelo Shizuku, antes que ele leia qualquer coisa.",
        'values-b+zh+Hans': "IMD+ 通过 Shizuku 关闭它，赶在它读取任何内容之前。",
        'values-de': "IMD+ schließt sie über Shizuku, bevor sie irgendetwas gelesen hat.",
        'values-es': "IMD+ la cierra a través de Shizuku, antes de que haya leído nada.",
        'values-fr': "IMD+ la ferme via Shizuku, avant qu\\'elle n\\'ait rien lu.",
        'values-hi': "IMD+ उसे Shizuku के ज़रिए बंद कर देता है, इससे पहले कि वह कुछ पढ़ पाए।",
        'values-ja': "IMD+ が Shizuku 経由でそれを終了します。何も読み取られる前です。",
        'values-ko': "IMD+가 Shizuku를 통해 앱을 닫습니다. 앱이 무언가를 읽기 전입니다.",
        'values-ru': "IMD+ закрывает его через Shizuku, до того как оно что-либо прочитает.",
    },
    'auto_hide_flow_3': {
        'values': "IMD hides whatever Settings to hide/ disable names.",
        'values-ar': "‏يُخفي IMD ما تنص عليه الإعدادات المراد إخفاؤها / تعطيلها.",
        'values-b+pt+BR': "O IMD oculta o que estiver em Configurações a ocultar/ desativar.",
        'values-b+zh+Hans': "IMD 隐藏要隐藏/停用的设置中列出的项目。",
        'values-de': "IMD blendet aus, was unter Auszublendende / zu deaktivierende Einstellungen steht.",
        'values-es': "IMD oculta lo indicado en Ajustes que se ocultan o desactivan.",
        'values-fr': "IMD masque ce qui figure dans Paramètres à masquer / désactiver.",
        'values-hi': "IMD वह सब छिपा देता है जो छिपाई / बंद की जाने वाली सेटिंग्स में दर्ज है।",
        'values-ja': "IMD が、非表示 / 無効にする設定で指定されたものを隠します。",
        'values-ko': "IMD가 숨기거나 끌 설정에 지정된 항목을 숨깁니다.",
        'values-ru': "IMD скрывает то, что перечислено в разделе Скрываемые / отключаемые настройки.",
    },
    'auto_hide_flow_4': {
        'values': "IMD switches off its own accessibility service, so it does not react to the next step.",
        'values-ar': "‏يُعطّل IMD خدمة إمكانية الوصول الخاصة به حتى لا يتفاعل مع الخطوة التالية.",
        'values-b+pt+BR': "O IMD desliga o seu próprio serviço de acessibilidade, para não reagir à etapa seguinte.",
        'values-b+zh+Hans': "IMD 关闭自己的无障碍服务，以免对下一步做出反应。",
        'values-de': "IMD schaltet seinen eigenen Bedienungshilfen-Dienst ab, damit es nicht auf den nächsten Schritt reagiert.",
        'values-es': "IMD apaga su propio servicio de accesibilidad para no reaccionar al paso siguiente.",
        'values-fr': "IMD désactive son propre service d\\'accessibilité, pour ne pas réagir à l\\'étape suivante.",
        'values-hi': "IMD अपनी ही एक्सेसिबिलिटी सेवा बंद कर देता है, ताकि वह अगले चरण पर प्रतिक्रिया न करे।",
        'values-ja': "IMD は自らのユーザー補助サービスをオフにし、次の手順に反応しないようにします。",
        'values-ko': "IMD가 자체 접근성 서비스를 꺼서 다음 단계에 반응하지 않도록 합니다.",
        'values-ru': "IMD выключает собственную службу специальных возможностей, чтобы не среагировать на следующий шаг.",
    },
    'auto_hide_flow_5': {
        'values': "IMD opens the app again. It starts with nothing to object to.",
        'values-ar': "‏يفتح IMD التطبيق من جديد، فيبدأ دون ما يعترض عليه.",
        'values-b+pt+BR': "O IMD abre o app de novo. Ele começa sem nada a que possa se opor.",
        'values-b+zh+Hans': "IMD 重新打开该应用，它启动时没有可反对的内容。",
        'values-de': "IMD öffnet die App wieder. Sie startet ohne Beanstandungen.",
        'values-es': "IMD vuelve a abrir la app. Arranca sin nada que objetar.",
        'values-fr': "IMD rouvre l\\'application. Elle démarre sans rien à redire.",
        'values-hi': "IMD ऐप को फिर से खोल देता है। वह बिना किसी आपत्ति के शुरू होता है।",
        'values-ja': "IMD がアプリを開き直します。文句のない状態で起動します。",
        'values-ko': "IMD가 앱을 다시 엽니다. 앱은 트집 잡을 것이 없는 상태로 시작합니다.",
        'values-ru': "IMD снова открывает приложение. Оно запускается без придирок.",
    },
    'auto_hide_flow_6': {
        'values': "A notification stays in the shade saying the settings are hidden.",
        'values-ar': "يبقى إشعار في لوحة الإشعارات يقول إن الإعدادات مخفية.",
        'values-b+pt+BR': "Uma notificação fica na área de notificações dizendo que as configurações estão ocultas.",
        'values-b+zh+Hans': "通知栏中会保留一条通知，说明设置已被隐藏。",
        'values-de': "Eine Benachrichtigung bleibt in der Leiste und sagt, dass die Einstellungen ausgeblendet sind.",
        'values-es': "Una notificación permanece en la barra indicando que los ajustes están ocultos.",
        'values-fr': "Une notification reste dans le volet pour indiquer que les paramètres sont masqués.",
        'values-hi': "सूचना पट्टी में एक सूचना बनी रहती है जो बताती है कि सेटिंग्स छिपी हुई हैं।",
        'values-ja': "設定が非表示であることを伝える通知が通知シェードに残ります。",
        'values-ko': "설정이 숨겨져 있다는 알림이 알림 창에 남습니다.",
        'values-ru': "В шторке остаётся уведомление о том, что настройки скрыты.",
    },
    'auto_hide_flow_revert': {
        'values': "Tapping that notification puts everything back: the watched apps are closed first, so none of them sees the settings return, and then your defaults are restored — the accessibility services, IMD's own among them, included.",
        'values-ar': "‏النقر على ذلك الإشعار يعيد كل شيء: تُغلق التطبيقات المُراقَبة أولًا حتى لا يرى أيٌّ منها عودة الإعدادات، ثم تُستعاد إعداداتك الافتراضية — بما فيها خدمات إمكانية الوصول، ومنها خدمة IMD نفسها.",
        'values-b+pt+BR': "Tocar nessa notificação devolve tudo: os apps observados são fechados primeiro, para que nenhum deles veja as configurações voltarem, e depois os seus padrões são restaurados — inclusive os serviços de acessibilidade, entre eles o do próprio IMD.",
        'values-b+zh+Hans': "点按该通知即可还原一切：先关闭受监视的应用，使它们都看不到设置回来，然后恢复你的默认配置——包括各项无障碍服务，其中也有 IMD 自己的。",
        'values-de': "Ein Tippen auf diese Benachrichtigung stellt alles wieder her: Zuerst werden die beobachteten Apps geschlossen, damit keine von ihnen die Rückkehr der Einstellungen sieht, dann werden deine Standardwerte wiederhergestellt — einschließlich der Bedienungshilfen-Dienste, darunter der von IMD selbst.",
        'values-es': "Al tocar esa notificación se devuelve todo: primero se cierran las apps vigiladas, para que ninguna vea volver los ajustes, y después se restauran tus valores por defecto, incluidos los servicios de accesibilidad y, entre ellos, el del propio IMD.",
        'values-fr': "Appuyer sur cette notification remet tout en place : les applications surveillées sont d\\'abord fermées, pour qu\\'aucune ne voie revenir les paramètres, puis vos valeurs par défaut sont restaurées — y compris les services d\\'accessibilité, dont celui d\\'IMD lui-même.",
        'values-hi': "उस सूचना पर टैप करने से सब कुछ वापस आ जाता है: पहले देखे जा रहे ऐप्स बंद किए जाते हैं, ताकि उनमें से कोई सेटिंग्स लौटते न देखे, फिर आपकी डिफ़ॉल्ट सेटिंग्स बहाल की जाती हैं — एक्सेसिबिलिटी सेवाएँ भी, जिनमें IMD की अपनी सेवा शामिल है।",
        'values-ja': "その通知をタップするとすべてが戻ります。まず監視対象のアプリを終了させ、どれにも設定が戻る様子を見せないようにしてから、既定値を復元します — IMD 自身のものを含むユーザー補助サービスも一緒です。",
        'values-ko': "그 알림을 누르면 모든 것이 되돌아갑니다. 먼저 감시 중인 앱을 닫아 어느 앱도 설정이 돌아오는 것을 보지 못하게 한 뒤, 기본값을 복원합니다 — IMD 자신의 것을 포함한 접근성 서비스도 함께입니다.",
        'values-ru': "Нажатие на это уведомление возвращает всё обратно: сначала закрываются отслеживаемые приложения, чтобы ни одно из них не увидело возвращения настроек, а затем восстанавливаются ваши значения по умолчанию — включая службы специальных возможностей, в том числе собственную службу IMD.",
    },

    # ---- the last-resort popup ----
    'auto_hide_blocked_title': {
        'values': "IMD+ could not switch its accessibility service on",
        'values-ar': "‏تعذّر على IMD+ تفعيل خدمة إمكانية الوصول الخاصة به",
        'values-b+pt+BR': "O IMD+ não conseguiu ligar o seu serviço de acessibilidade",
        'values-b+zh+Hans': "IMD+ 无法开启其无障碍服务",
        'values-de': "IMD+ konnte seinen Bedienungshilfen-Dienst nicht einschalten",
        'values-es': "IMD+ no ha podido activar su servicio de accesibilidad",
        'values-fr': "IMD+ n\\'a pas pu activer son service d\\'accessibilité",
        'values-hi': "IMD+ अपनी एक्सेसिबिलिटी सेवा चालू नहीं कर सका",
        'values-ja': "IMD+ はユーザー補助サービスをオンにできませんでした",
        'values-ko': "IMD+가 접근성 서비스를 켜지 못했습니다",
        'values-ru': "IMD+ не смог включить свою службу специальных возможностей",
    },
    'auto_hide_blocked_1': {
        'values': "1. Either grant the accessibility service through Shizuku, or",
        'values-ar': "‏1. إما أن تمنح خدمة إمكانية الوصول عبر Shizuku، أو",
        'values-b+pt+BR': "1. Conceda o serviço de acessibilidade pelo Shizuku, ou",
        'values-b+zh+Hans': "1. 通过 Shizuku 授予该无障碍服务，或者",
        'values-de': "1. Entweder den Bedienungshilfen-Dienst über Shizuku erteilen, oder",
        'values-es': "1. Concede el servicio de accesibilidad a través de Shizuku, o bien",
        'values-fr': "1. Accordez le service d\\'accessibilité via Shizuku, ou",
        'values-hi': "1. या तो Shizuku के ज़रिए एक्सेसिबिलिटी सेवा दें, या",
        'values-ja': "1. Shizuku 経由でユーザー補助サービスを許可する、または",
        'values-ko': "1. Shizuku를 통해 접근성 서비스를 허용하거나,",
        'values-ru': "1. Либо предоставьте службу специальных возможностей через Shizuku, либо",
    },
    'auto_hide_blocked_2': {
        'values': "2. Allow restricted settings for IMD+ (on Android 13 and later a sideloaded app must be given restricted-settings permission before its accessibility service can be switched on).",
        'values-ar': "‏2. اسمح بالإعدادات المقيّدة لـ IMD+ (على أندرويد 13 فما فوق، يجب منح التطبيق المُثبَّت من خارج المتجر إذن الإعدادات المقيّدة قبل أن يمكن تفعيل خدمة إمكانية الوصول الخاصة به).",
        'values-b+pt+BR': "2. Permita as configurações restritas para o IMD+ (no Android 13 e posteriores, um app instalado fora da loja precisa receber a permissão de configurações restritas antes que o seu serviço de acessibilidade possa ser ligado).",
        'values-b+zh+Hans': "2. 为 IMD+ 允许受限设置（在 Android 13 及更高版本上，旁加载的应用必须先获得受限设置权限，其无障碍服务才能被开启）。",
        'values-de': "2. Eingeschränkte Einstellungen für IMD+ zulassen (ab Android 13 muss einer per Sideload installierten App zuerst die Berechtigung für eingeschränkte Einstellungen erteilt werden, bevor ihr Bedienungshilfen-Dienst eingeschaltet werden kann).",
        'values-es': "2. Permite los ajustes restringidos para IMD+ (en Android 13 y posteriores, una app instalada fuera de la tienda necesita el permiso de ajustes restringidos antes de que su servicio de accesibilidad pueda activarse).",
        'values-fr': "2. Autorisez les paramètres restreints pour IMD+ (à partir d\\'Android 13, une application installée hors magasin doit recevoir l\\'autorisation des paramètres restreints avant que son service d\\'accessibilité puisse être activé).",
        'values-hi': "2. IMD+ के लिए प्रतिबंधित सेटिंग्स की अनुमति दें (Android 13 और उसके बाद, बाहर से इंस्टॉल किए गए ऐप को पहले प्रतिबंधित-सेटिंग्स की अनुमति देनी होती है, तभी उसकी एक्सेसिबिलिटी सेवा चालू की जा सकती है)।",
        'values-ja': "2. IMD+ に制限付き設定を許可する（Android 13 以降では、サイドロードしたアプリはまず制限付き設定の許可を与えられないと、ユーザー補助サービスをオンにできません）。",
        'values-ko': "2. IMD+에 제한된 설정을 허용하세요 (Android 13 이상에서는 스토어 밖에서 설치한 앱에 제한된 설정 권한을 먼저 부여해야 접근성 서비스를 켤 수 있습니다).",
        'values-ru': "2. Разрешите ограниченные настройки для IMD+ (начиная с Android 13 приложению, установленному не из магазина, сначала нужно выдать разрешение на ограниченные настройки, и только затем можно включить его службу специальных возможностей).",
    },
    'auto_hide_blocked_retry': {
        'values': "Then try again.",
        'values-ar': "ثم حاول مرة أخرى.",
        'values-b+pt+BR': "Depois tente de novo.",
        'values-b+zh+Hans': "然后再试一次。",
        'values-de': "Dann erneut versuchen.",
        'values-es': "Después inténtalo de nuevo.",
        'values-fr': "Puis réessayez.",
        'values-hi': "फिर दोबारा कोशिश करें।",
        'values-ja': "その後、もう一度お試しください。",
        'values-ko': "그런 다음 다시 시도하세요.",
        'values-ru': "Затем попробуйте снова.",
    },

    # ---- the always-checked row in the accessibility picker ----
    'accessibility_service_own': {
        'values': "IMD\\'s own detector — always hidden with the rest while IMD+ is on",
        'values-ar': "‏كاشف IMD نفسه — يُخفى دائمًا مع البقية أثناء تفعيل IMD+",
        'values-b+pt+BR': "O detector do próprio IMD — sempre ocultado junto com os demais enquanto o IMD+ estiver ligado",
        'values-b+zh+Hans': "IMD 自己的检测器——IMD+ 开启时始终与其他服务一同被隐藏",
        'values-de': "IMDs eigener Detektor — wird bei eingeschaltetem IMD+ immer mit den anderen ausgeblendet",
        'values-es': "El detector del propio IMD: siempre se oculta con los demás mientras IMD+ esté activado",
        'values-fr': "Le détecteur d\\'IMD lui-même — toujours masqué avec les autres tant qu\\'IMD+ est activé",
        'values-hi': "IMD का अपना डिटेक्टर — IMD+ चालू रहने पर हमेशा बाकियों के साथ छिपाया जाता है",
        'values-ja': "IMD 自身の検知サービス — IMD+ がオンの間は常に他と一緒に無効化されます",
        'values-ko': "IMD 자체 감지기 — IMD+가 켜져 있는 동안 항상 다른 것들과 함께 숨겨집니다",
        'values-ru': "Собственный детектор IMD — при включённом IMD+ всегда скрывается вместе с остальными",
    },
}

# The two sentences that are highlighted at runtime against settings_to_hide_title.
HIGHLIGHTED = ['auto_hide_info_hide_list', 'auto_hide_flow_3']


def main():
    problems = []

    # Every key carries every locale, or a locale silently falls back to English.
    for key, translations in NEW.items():
        missing = [loc for loc in L if loc not in translations]

        if missing:
            problems.append(f'{key}: missing {missing}')

    # The highlighting lesson from v2.2: a phrase that does not occur in the sentence matches
    # nothing and the emphasis is silently lost. Assert it instead of hoping.
    for key in HIGHLIGHTED:
        for loc in L:
            sentence = NEW[key].get(loc, '')
            phrase = HIDE_LIST[loc]

            if phrase not in sentence:
                problems.append(f'{key}/{loc}: does not contain "{phrase}"')

    # Format specifiers must survive translation exactly.
    for key, translations in NEW.items():
        english = set(re.findall(r'%\d\$[sd]', translations['values']))

        for loc in L:
            found = set(re.findall(r'%\d\$[sd]', translations.get(loc, '')))

            if found != english:
                problems.append(f'{key}/{loc}: format specifiers {sorted(found)} != {sorted(english)}')

    if problems:
        print('PROBLEMS (nothing written):')
        for p in problems:
            print('  -', p)
        sys.exit(1)

    added = 0

    for loc in L:
        path = os.path.join(BASE, loc, 'strings.xml')

        if not os.path.exists(path):
            print(f'missing {path}')
            sys.exit(1)

        src = open(path, encoding='utf-8').read()

        add = [
            f'    <string name="{k}">{t[loc]}</string>'
            for k, t in NEW.items() if f'name="{k}"' not in src
        ]

        if add:
            src = src.replace('</resources>', '\n'.join(add) + '\n</resources>', 1)
            open(path, 'w', encoding='utf-8').write(src)
            added += len(add)

        print(f'{loc:18s} +{len(add)}')

    print(f'OK, {added} strings added')


if __name__ == '__main__':
    main()
