#!/usr/bin/env python3
"""v3-r4r — `check_new_types` stops reporting `R`.

The new `SetupSteps.kt` drew:

    feature/settings/src/main/kotlin/com/android/geto/feature/settings/SetupSteps.kt:
      R is new here and not imported

⚠ **It is not a missing import, and it cannot be one.** `R` is generated by the build into the
module's *own* package, so every file in that package sees it without importing anything -
`SettingsScreen.kt`, in the same package, uses `R.string.…` on nearly every screen and imports no
`R` at all. A file in a different package cannot use the bare name either: it has to alias it, as
this repo does everywhere with `R as commonR` and `R as settingsR`, and an alias is a different
token that the checker already handles.

So a bare `R` is never a name an import could have supplied, and excluding it is the extractor
becoming correct rather than the check being relaxed. This is the same class of fix as
`check_local_scope`'s five false-positive families.

## Measured, as the toolkit requires

* **0 on the pristine tree** - the change cannot have started reporting something new;
* **the one report gone on the working tree**;
* **a canary still seen** - a genuinely unimported new type is still reported, because a check
  that has only ever printed zero has not been tested.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CHECKER = "tools/check_new_types.py"

PRISTINE = Path("/root/work/r4o-extract")

OLD = """def names_used(text: str) -> set[str]:
    body = strip(text)

    # Everything above the first declaration is the package line and the imports; a name there
    # is being declared as importable rather than used.
    without_imports = IMPORT.sub(" ", PACKAGE.sub(" ", body))

    return set(USED.findall(without_imports))"""

NEW = '''def names_used(text: str) -> set[str]:
    body = strip(text)

    # Everything above the first declaration is the package line and the imports; a name there
    # is being declared as importable rather than used.
    without_imports = IMPORT.sub(" ", PACKAGE.sub(" ", body))

    return set(USED.findall(without_imports)) - NEVER_IMPORTED


# ⚠ **`R` is generated into the module's own package**, so every file in that package sees it
# with no import - SettingsScreen.kt uses `R.string.…` throughout and imports no R at all. A file
# in a *different* package cannot use the bare name: it has to alias it, as this repo does with
# `R as commonR` and `R as settingsR`, and an alias is a different token this checker already
# understands.
#
# So a bare R is never a name an import could have supplied. Excluding it is the extractor
# becoming correct, not the check being relaxed.
NEVER_IMPORTED = {"R"}'''

CANARY_FILE = "tools/_new_types_canary.kt"

CANARY = """package com.android.geto.canary

fun canary(): CompletelyUnknownCanaryType = TODO()
"""


def run(baseline: Path) -> str:
    result = subprocess.run(
        [sys.executable, str(ROOT / CHECKER), str(baseline)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )

    return result.stdout + result.stderr


def main() -> int:
    path = ROOT / CHECKER

    if not path.is_file():
        print(f"REFUSED: missing {CHECKER}")
        return 1

    original = path.read_text(encoding="utf-8")

    if original.count(OLD) != 1:
        print(f"REFUSED: {CHECKER}\n  names_used matched {original.count(OLD)} time(s), expected 1")
        return 1

    path.write_text(original.replace(OLD, NEW, 1), encoding="utf-8")

    try:
        out = run(PRISTINE)

        if " R is new here" in out:
            path.write_text(original, encoding="utf-8")

            print(f"REFUSED: R is still reported:\n{out}")
            return 1

        if "unimported" not in out:
            path.write_text(original, encoding="utf-8")

            print(f"REFUSED: the checker did not run as expected:\n{out}")
            return 1

        # ⚠ And a file with a genuinely unimported new type, so this cannot have been turned off.
        canary = ROOT / CANARY_FILE

        canary.write_text(CANARY, encoding="utf-8")

        try:
            out = run(PRISTINE)
        finally:
            canary.unlink()

        if "CompletelyUnknownCanaryType" not in out:
            path.write_text(original, encoding="utf-8")

            print(f"REFUSED: the checker can no longer see an unimported type:\n{out}")
            return 1

    except BaseException:
        path.write_text(original, encoding="utf-8")

        raise

    print(f"  ok        {CHECKER}  :: R is never an import-requiring name")
    print("  ok        the SetupSteps report is gone")
    print("  ok        an unimported type is still reported")
    print("\nwrote 1 file(s), 1 edit(s)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
