#!/usr/bin/env python3
"""r4f — the themed launcher icon gets its key back.

The author: *"for the imd app icon when i use themed icon in the launcher the key in the gear
disappears, but it stays legible for settings manager icon, can we fix it"*.

### Why one survives theming and the other does not

`ic_launcher_foreground.xml` is three paths:

    #A5DBB9   2268 chars,  1 subpath    the gear
    #13A75B   1490 chars, 10 subpaths   the key
    #A5DBB9    268 chars,  1 subpath    the hole in the key's bow

`ic_launcher_monochrome.xml` was **one** path, 2268 chars, solid `#FFFFFF` — the gear alone. The
key had never been in it. A themed icon is filled with a single colour, so a solid gear is all
there is to draw and no amount of tinting can make a key appear.

`ic_services_monochrome.xml` is one path, four subpaths, `fillType="evenOdd"`: the gear with its
glyph punched out. That is the whole difference, and it is the shape this script copies.

### What it writes

The gear and the key as one even-odd path, so the key becomes a hole in the gear — but the key is
**unioned into a single outline first**, and that step is the whole of r4g.

⚠ **Concatenating the key's ten subpaths does not work, and the author saw why.** *"there are a
few faults in the key"*. Even-odd counts crossings: a point inside the gear and inside **one** key
subpath is at 2 and comes out as a hole, which is right; a point inside the gear and inside **two
overlapping** key subpaths is at 3 and comes out filled again, which is a pale notch. The key
overlaps itself in four places — the shaft into the bow and the shaft into two of the teeth — so
r4f shipped a key with a light square where the shaft meets the bow and pale nubs on two teeth.

The colour icon never showed this because it draws the key as its own path with ordinary
non-zero winding, where overlapping subpaths simply merge.

⚠ **Nor can winding fix it.** Non-zero with the key wound against the gear gives 0 inside one
subpath (a hole, right) and −1 inside two (filled, wrong). Only a real union does it, so the key
is flattened, unioned with Shapely, and re-emitted as one outline.

⚠ **The bow's hole is subtracted rather than appended** — the author's *"Y — bow ring"*, which
also makes the themed key the same key as the colour one. As a genuine interior ring of the
unioned polygon it is immune to the overlap problem that a third concatenated subpath had.

⚠ **Flattened to line segments, which is the cost.** A boolean union of Béziers cannot be
expressed as Béziers without refitting them, so the key is sampled at 400 points per subpath and
simplified at 0.05 units — 1/2160th of the icon's width, well under a pixel at any size a
launcher draws. The gear keeps its original curves untouched.

⚠ **Generated from the colour icon rather than drawn**, for the reason `_v3_fav_hide_glyph.py`
gives: a hand-copy of artwork drifts from its original, and re-deriving it means the gear here
cannot stop being the gear there. The colour icon is read and never written.

⚠ **`ic_launcher_round` and the colour foreground are untouched.** Only the monochrome layer was
ever wrong.

Asserts the source is the three-path shape it expects, and refuses rather than writing something
it cannot identify.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from shapely.geometry import Polygon
from shapely.ops import unary_union
from svgpathtools import parse_path

# Points sampled per subpath before the union, and how hard the result is simplified afterwards.
# 0.05 of a 108-wide viewport is 1/2160th of the icon: under a pixel at any size a launcher draws.
SAMPLES = 400
TOLERANCE = 0.05

# Holes smaller than this are flattening debris, not artwork. Sampling a curve into 400 points
# leaves sub-pixel slivers where two subpaths meet almost tangentially — four of them here, of
# about 1e-8 square units against the bow's 39. On a 108-wide viewport 0.01 is one part in a
# million of the icon; nothing at that size was ever drawn on purpose.
MIN_HOLE_AREA = 0.01

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "app/src/main/res/drawable/ic_launcher_foreground.xml"
TARGET = ROOT / "app/src/main/res/drawable/ic_launcher_monochrome.xml"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  ~   GENERATED by design/_v3_launcher_monochrome.py from ic_launcher_foreground.xml. Do not
  ~   edit by hand; re-run the script.
  ~
  ~   The themed-icon layer. Until r4f this was the gear alone, so a launcher set to themed
  ~   icons drew a solid blob - a single-colour layer has no way to show a key that was never
  ~   in it. The gear and the key are now one even-odd path, which punches the key out of the
  ~   gear, and that is the same construction ic_services_monochrome has always used.
  ~
  ~   The key is a boolean union of its own ten subpaths, with the bow's hole subtracted, not
  ~   the ten concatenated. Even-odd turns an overlap between two of them back into fill, and
  ~   the key overlaps itself in four places - which is why r4f drew a pale notch where the
  ~   shaft meets the bow. The union is flattened to line segments; a boolean of Beziers cannot
  ~   stay Beziers, and at 0.05 units the difference is under a pixel at any launcher size.
  ~
  ~   Carries no android:tint. The platform tints a monochrome layer itself.
  -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FFFFFF"
        android:fillType="evenOdd"
        android:pathData="{path}" />
</vector>
"""


def polygons(data: str):
    """A path's subpaths as one Shapely geometry, curves flattened to points.

    Sampling rather than solving: a boolean union of Béziers cannot be written as Béziers
    without refitting them, and at [TOLERANCE] the straight-line stand-in is under a pixel.
    """
    shapes = []

    for sub in parse_path(data).continuous_subpaths():
        points = [
            (sub.point(step / SAMPLES).real, sub.point(step / SAMPLES).imag)
            for step in range(SAMPLES)
        ]

        polygon = Polygon(points)

        # buffer(0) is Shapely's idiom for repairing a ring that crosses itself, which a
        # flattened glyph outline occasionally does at a tight corner.
        shapes.append(polygon if polygon.is_valid else polygon.buffer(0))

    return unary_union(shapes)


def drop_slivers(geometry):
    """The same shape with its sub-pixel interior rings removed.

    ⚠ **Flattening leaves debris.** Where two of the key's subpaths meet almost tangentially the
    sampled outlines cross in a sliver a hundred-millionth of a unit across, and Shapely records
    each as an interior ring. They are invisible, but they would each become a subpath in the
    output and each defeat the "three subpaths" assertion that proves the union happened.
    """
    if geometry.geom_type != "Polygon":
        return geometry

    kept = [
        ring for ring in geometry.interiors
        if Polygon(ring).area >= MIN_HOLE_AREA
    ]

    return Polygon(geometry.exterior, kept)


def to_path(geometry, tolerance: float) -> str:
    """A Shapely geometry as vector pathData: one closed subpath per ring, holes included."""
    geometry = geometry.simplify(tolerance, preserve_topology=True)

    parts = geometry.geoms if geometry.geom_type == "MultiPolygon" else [geometry]
    out: list[str] = []

    for polygon in parts:
        for ring in [polygon.exterior, *polygon.interiors]:
            points = list(ring.coords)

            out.append(f"M{points[0][0]:.2f},{points[0][1]:.2f}")
            out += [f"L{x:.2f},{y:.2f}" for x, y in points[1:-1]]
            out.append("Z")

    return "".join(out)


def main() -> int:
    problems: list[str] = []

    for path in (SOURCE, TARGET):
        if not path.exists():
            print("REFUSED, nothing written")
            print(f"  {path.relative_to(ROOT)} is missing")

            return 1

    source = SOURCE.read_text(encoding="utf-8")

    paths = re.findall(r'android:pathData="([^"]+)"', source)

    if len(paths) != 3:
        problems.append(f"expected 3 paths in the foreground (gear, key, bow), found {len(paths)}")

    if 'android:viewportWidth="108"' not in source:
        problems.append("the foreground is no longer drawn on a 108 viewport")

    if 'android:tint="' in source:
        problems.append("the foreground has gained an android:tint, which must not be copied")

    if problems:
        print("REFUSED, nothing written")

        for problem in problems:
            print(f"  {problem}")

        return 1

    gear, key, bow = paths

    # The gear is one closed shape and the key is the ten the knockout needs. Asserted so a
    # redrawn foreground cannot land here silently and quietly produce a blob again.
    if gear.count("M") != 1:
        problems.append(f"expected the gear to be 1 subpath, found {gear.count('M')}")

    if key.count("M") != 10:
        problems.append(f"expected the key to be 10 subpaths, found {key.count('M')}")

    # ⚠ The union, which is the point of this script. See the module docstring.
    shape = drop_slivers(polygons(key).difference(polygons(bow)))

    # Asserted on the geometry, before it becomes text: one shape, one hole. A key that came
    # back as several pieces would mean the source no longer joins up, and a key with no hole
    # would mean the bow subtraction missed - either is a redraw this script must not guess at.
    if shape.geom_type != "Polygon":
        problems.append(f"expected the key to union into one shape, got {shape.geom_type}")
    elif len(shape.interiors) != 1:
        problems.append(f"expected exactly one hole (the bow), found {len(shape.interiors)}")
    elif abs(Polygon(shape.interiors[0]).area - polygons(bow).area) > 0.5:
        problems.append("the surviving hole is not the bow — the subtraction found the wrong one")

    if problems:
        print("REFUSED, nothing written")

        for problem in problems:
            print(f"  {problem}")

        return 1

    outline = to_path(shape, tolerance=TOLERANCE)

    combined = gear + outline

    # The thing that actually went wrong: a monochrome layer with only the gear in it. Whatever
    # else changes, this file must carry more than the gear and must knock out rather than
    # overpaint.
    if len(combined) <= len(gear):
        problems.append("the key added nothing — this would ship the blob again")

    # ⚠ **Three subpaths, and not one more.** The gear, the key's single unioned outline, and
    # the bow's hole. Ten again would mean the union silently did not happen and the pale notch
    # r4f shipped is back.
    if combined.count("M") != 3:
        problems.append(
            f"expected 3 subpaths (gear, key, bow hole), found {combined.count('M')}",
        )

    if problems:
        print("REFUSED, nothing written")

        for problem in problems:
            print(f"  {problem}")

        return 1

    TARGET.write_text(HEADER.replace("{path}", combined), encoding="utf-8")

    print(f"ok - wrote {TARGET.relative_to(ROOT)} "
          f"({len(combined)} chars, {combined.count('M')} subpaths, was {len(gear)} and 1)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
