#!/usr/bin/env python3
"""
v3-r6 — the monochrome IMD gear, where the settings manager can reach it.

The author asked the manager's title-line button for *"a imd settings gear icon similar in colour
to the i logo button colour with the key area in center hollow"*, and the shape already existed:
`app/.../ic_launcher_monochrome.xml`, the layer a launcher draws when themed icons are switched
on. It is the gear and the key as **one even-odd path**, so the key is punched clean out of the
gear rather than painted on top of it — which is what "hollow" means and what a single-colour
glyph needs, since a second path in a second colour is the thing being given up.

⚠ **The only reason this file exists is module reach.** The dialog lives in `:feature:apps`, which
depends on `:design-system` and not on `:app`, so it cannot see a drawable in the app module. This
copies the path across rather than duplicating the *construction* — the boolean union that made it
lives in `_v3_launcher_monochrome.py` and stays there, and re-running that script and then this one
keeps the two in step.

⚠ **`@android:color/white`, and it is not a colour decision.** `Icon` tints whatever it is given,
so the fill here is only what the tint replaces; the real colour is chosen at the call site, which
is `onSurfaceVariant` — the ⓘ's own token, at the author's pick from the r6 template. The same
convention `ic_services_glyph` already uses.

Nothing is written if the source does not look the way this expects.
"""
from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ANDROID = "http://schemas.android.com/apk/res/android"

SOURCE = ROOT / "app/src/main/res/drawable/ic_launcher_monochrome.xml"

OUT = ROOT / "design-system/src/main/res/drawable/ic_imd_mono.xml"

LICENCE = """<!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  ~   GENERATED by design/_v3_imd_mono_glyph.py from
  ~   app/src/main/res/drawable/ic_launcher_monochrome.xml. Do not edit by hand; re-run the
  ~   script. The path itself is built by design/_v3_launcher_monochrome.py, which is where the
  ~   boolean union of the key and the even-odd punch-out are explained.
  ~
  ~   The settings manager's title-line button, at the author's instruction: the gear with the
  ~   key area hollow, in the same colour as the dialog's own info button. This file is a copy
  ~   rather than a reference because :feature:apps can see :design-system and cannot see :app.
  ~
  ~   White, and that is not a colour decision - Icon tints it. onSurfaceVariant is chosen at
  ~   the call site, which is where a reader looking for the colour will be.
  -->"""


def main() -> int:
    if not SOURCE.is_file():
        print(f"REFUSED: missing {SOURCE.relative_to(ROOT)}")
        return 1

    root = ET.parse(SOURCE).getroot()

    paths = [p for p in root.iter("path") if p.get(f"{{{ANDROID}}}pathData")]

    if len(paths) != 1:
        print(f"REFUSED: expected exactly 1 path in the source, found {len(paths)}")
        return 1

    path = paths[0]

    fill_type = path.get(f"{{{ANDROID}}}fillType")

    if fill_type != "evenOdd":
        print(
            f"REFUSED: the source path is fillType={fill_type!r}, not 'evenOdd' — the key would "
            "come out solid rather than hollow, which is the whole of what was asked for",
        )
        return 1

    data = path.get(f"{{{ANDROID}}}pathData")

    for attr, want in (("viewportWidth", "108"), ("viewportHeight", "108")):
        got = root.get(f"{{{ANDROID}}}{attr}")

        if got != want:
            print(f"REFUSED: source {attr} is {got!r}, expected {want!r}")
            return 1

    written = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"{LICENCE}\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        "    <path\n"
        '        android:fillColor="@android:color/white"\n'
        '        android:fillType="evenOdd"\n'
        f'        android:pathData="{data}" />\n'
        "</vector>\n"
    )

    if OUT.is_file() and OUT.read_text(encoding="utf-8") == written:
        print(f"  unchanged  {OUT.relative_to(ROOT)}")

        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)

    OUT.write_text(written, encoding="utf-8")

    print(f"  ok  {OUT.relative_to(ROOT)}  <- 1 even-odd path, {len(data)} chars")

    return 0


if __name__ == "__main__":
    sys.exit(main())
