#!/usr/bin/env python3
"""
v3-r6 — the settings manager's title line: a bigger hollow gear, and the ⓘ over the switches.

Two of the author's asks, both settled off the r6 templates.

## The gear

    "the imd app icon button i want to replace it with a imd settings gear icon similar in colour
     to the i logo button colour with the key area in center hollow, and make the settings gear
     size bigger"

So the full-colour launcher icon becomes [ic_imd_mono] — the gear with the key punched out of it,
generated by `_v3_imd_mono_glyph.py` — drawn through `Icon` rather than `Image`, because `Icon` is
what tints, and tinted `onSurfaceVariant`, which is the ⓘ's own token. He picked that tint over
`onSurface` and `primary` from the template.

**48 dp**, his pick from the size ladder, and *"one size everywhere"* — so the tier's `appIconSize`
goes. 48 is the largest size that costs nothing: the ⓘ is an `IconButton`, Material floors those at
a 48 dp touch target, and the row is therefore already 48 dp tall whatever the gear does.

⚠ **The glyph is inset in its own viewport.** The gear occupies about 48% of the 108-unit box, so a
48 dp icon draws a gear about 23 dp across. That is what the template rendered and what he chose
from; the viewport is deliberately not cropped to make it look bigger than what he approved.

## The ⓘ

    "the i logo button i want it within the same row but move to left and center it above the
     center point of the toggles below"
    "the i logo button is tiny and its size is perfect do not touch i logo icon photo or its size,
     only its position"

So the button, its glyph and its 18 dp size are untouched — only where it sits changes. It goes in
a box the width of a Material switch's track at the very end of the row, which centres it on the
switches below.

⚠ **52 dp, and why that is the right number rather than a measured offset.** `SwitchTokens`
`TrackWidth` is 52 dp; `Modifier.scale` is a *draw* transform, so a scaled switch still occupies
its full 52 dp of layout and still scales about its own centre. The rows carry no end padding, so
every switch's box ends exactly at the card's content edge — and a 52 dp box at the end of this
row therefore has its centre on theirs, at every tier and every switch scale, with no arithmetic
to go stale.

⚠ **Which is also why this row's end padding has to go to zero.** With 10 dp there the two right
edges would differ by 10 and the ⓘ would sit 10 dp inside the switches.

⚠ **The title takes the slack with `weight(1f)`**, so a long title wraps rather than pushing the ⓘ
off the end. Every tier has room today — the tightest is the compact card at 178 dp of space for
about 114 dp of title — but translations are deferred and this is the shape that survives one.

Every edit asserts its anchor matches exactly once. Nothing is written if any file fails.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DIALOG = (
    "feature/apps/src/main/kotlin/com/android/geto/feature/apps/dialog/"
    "AndroidSettingsManagerDialog.kt"
)

# --- 1. the two new constants, beside the switch scales they are about ----------------

CONST_OLD = '''/** And on a roomy one: its natural size, which is what the 48 dp target was drawn for. */
private const val ROOMY_SWITCH_SCALE = 1f
'''

CONST_NEW = '''/** And on a roomy one: its natural size, which is what the 48 dp target was drawn for. */
private const val ROOMY_SWITCH_SCALE = 1f

/**
 * The width of a Material switch's track, which is what puts the ⓘ over the switches.
 *
 * ⚠ **A layout width, not a drawn one, and that is the point.** `Modifier.scale` is a draw
 * transform: a scaled switch still occupies all 52 dp of layout and still scales about its own
 * centre. The rows carry no end padding, so every switch's box ends exactly at the card's content
 * edge — put a box of this width at the end of the title row and its centre is on theirs, at every
 * tier and every scale, with no offset to go stale.
 */
private val SWITCH_TRACK_WIDTH = 52.dp

/**
 * How big the IMD gear on the title line is drawn.
 *
 * ⚠ **48 dp costs nothing, and that is why it is the author's pick.** The ⓘ beside it is an
 * `IconButton`, which Material floors at a 48 dp touch target, so this row is already 48 dp tall
 * whatever this number is. Anything past 48 makes the row grow and pushes the whole card down.
 *
 * ⚠ **One size on every tier**, at his instruction — where the title, the rows, the pill and the
 * switches all step with [ManagerSize]. His reasoning stands on its own: the glyph is an identity
 * mark rather than type, and identity does not get bigger because the screen did.
 *
 * ⚠ **The gear is inset in its own viewport** — it fills about 48% of the 108-unit box, so this
 * draws a gear roughly 23 dp across. That is what the r6 size template rendered and what he chose
 * from; cropping the viewport to make the glyph fill the box would quietly give him something
 * larger than he approved.
 */
private val MANAGER_GLYPH_SIZE = 48.dp
'''

# --- 2. the tier's own icon size goes ---------------------------------------------------

APPICON_OLD = '''/**
 * The app icon on the title line.
 *
 * It grows only on the roomy card. On the other two it is already the largest thing on that line
 * and a step down would leave the title looking unattached to it.
 */
private val ManagerSize.appIconSize: Dp
    get() = when (this) {
        ManagerSize.Compact -> 28.dp

        ManagerSize.Regular -> 28.dp

        ManagerSize.Roomy -> 32.dp
    }

'''

APPICON_NEW = ""

# --- 3. the row itself -------------------------------------------------------------------

ROW_OLD = '''            // The app's own icon, as the launcher draws it. This dialog is usually opened
            // from a tile or a shortcut, over somebody else's app, with nothing else on
            // screen to say which app just put a dialog in front of them.

            // A plain Row again. r2's centred logo button is gone and its job has moved
            // onto the app icon below, at the author's instruction — the icon was already
            // there, already says which app put this dialog in front of you, and one glyph
            // on this line is easier to aim at than two.
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                // The icon is the button now. Clipped to a circle so the ripple matches the
                // shape a launcher draws it in, and left at 32dp rather than grown to a 48dp
                // target: this sits on the title line, and a taller press area would push the
                // title and the ⓘ out of line with it.
                Image(
                    modifier = Modifier
                        .size(metrics.size.appIconSize)
                        .clip(CircleShape)
                        .clickable(onClick = onOpenImdApp),
                    painter = painterResource(designR.drawable.ic_imd_app),
                    contentDescription = stringResource(
                        R.string.settings_manager_open_settings,
                    ),
                )

                Spacer(modifier = Modifier.width(12.dp))

                Text(
                    text = stringResource(R.string.settings_manager_title),
                    // One step down, with everything else on this dialog — r4y — and a step
                    // either way from there with the tier, r5.
                    style = metrics.size.titleStyle(),
                )

                Spacer(modifier = Modifier.width(4.dp))

                IconButton(onClick = { showInfo = true }) {
                    Icon(
                        modifier = Modifier.size(18.dp),
                        imageVector = GetoIcons.Info,
                        contentDescription = stringResource(R.string.settings_manager_info),
                        tint = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }
'''

ROW_NEW = '''            // A plain Row again. r2's centred logo button is gone and its job has moved
            // onto the glyph below, at the author's instruction — it was already there,
            // already says which app put this dialog in front of you, and one glyph on this
            // line is easier to aim at than two.
            //
            // ⚠ **No padding at the end — r6, and it is load-bearing.** The rows below carry
            // none either, so their switches finish exactly at the card's content edge. Ten dp
            // here would end this row ten dp short of that, and the ⓘ would sit that far inside
            // the switches it is supposed to be centred on.
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(start = 10.dp, top = 10.dp, bottom = 10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                // ⚠ **The gear with the key hollow, not the launcher icon — r6.** The author
                // asked for "a imd settings gear icon ... with the key area in center hollow",
                // in the ⓘ's colour, and bigger. `Icon` rather than `Image` because `Icon` is
                // what applies a tint; see `ic_imd_mono` for why the shape is a copy of the
                // launcher's themed-icon layer and not a new drawing.
                //
                // Still the button, and still clipped to a circle so the ripple is a disc
                // around the glyph rather than a square behind it.
                Icon(
                    modifier = Modifier
                        .size(MANAGER_GLYPH_SIZE)
                        .clip(CircleShape)
                        .clickable(onClick = onOpenImdApp),
                    painter = painterResource(designR.drawable.ic_imd_mono),
                    contentDescription = stringResource(
                        R.string.settings_manager_open_settings,
                    ),
                    tint = MaterialTheme.colorScheme.onSurfaceVariant,
                )

                Spacer(modifier = Modifier.width(12.dp))

                Text(
                    // ⚠ **Weighted, so the title takes the slack** rather than the ⓘ being
                    // pushed along by it. Every tier has room for this title today — the
                    // tightest is the compact card, 178 dp of space for about 114 dp of text —
                    // but translations are deferred, and this is the shape that survives the
                    // first one that is longer: it wraps instead of shoving the ⓘ off the end.
                    modifier = Modifier.weight(1f),
                    text = stringResource(R.string.settings_manager_title),
                    // One step down, with everything else on this dialog — r4y — and a step
                    // either way from there with the tier, r5.
                    style = metrics.size.titleStyle(),
                )

                // ⚠ **The ⓘ, moved and nothing else — r6.** *"do not touch i logo icon photo or
                // its size, only its position"*: the button, the glyph and its 18 dp are exactly
                // as they were. What is new is the box around it, which is a switch's track wide
                // and sits at the very end of the row — so the ⓘ lands on the switches' own
                // centre line. See [SWITCH_TRACK_WIDTH] for why that is a width rather than an
                // offset.
                Box(
                    modifier = Modifier.width(SWITCH_TRACK_WIDTH),
                    contentAlignment = Alignment.Center,
                ) {
                    IconButton(onClick = { showInfo = true }) {
                        Icon(
                            modifier = Modifier.size(18.dp),
                            imageVector = GetoIcons.Info,
                            contentDescription = stringResource(
                                R.string.settings_manager_info,
                            ),
                            tint = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    }
                }
            }
'''

# --- 4. Image is no longer drawn anywhere in this file -----------------------------------

IMPORT_OLD = "import androidx.compose.foundation.Image\n"

IMPORT_NEW = ""

EDITS = [
    (CONST_OLD, CONST_NEW),
    (APPICON_OLD, APPICON_NEW),
    (ROW_OLD, ROW_NEW),
    (IMPORT_OLD, IMPORT_NEW),
]

CHECKS = [
    ("ic_imd_mono", 2, "the hollow gear is the drawable, and its KDoc names it"),
    ("ic_imd_app", 0, "and the full-colour launcher icon is gone from this dialog"),
    ("appIconSize", 0, "the per-tier icon size is gone"),
    ("MANAGER_GLYPH_SIZE", 2, "one size, declared and used once"),
    ("SWITCH_TRACK_WIDTH", 3, "one box width: declared, referenced in the row KDoc, used once"),
    ("Image(", 0, "nothing in this file draws an untinted Image any more"),
    ("androidx.compose.foundation.Image", 0, "nor imports one"),
    # The ⓘ itself, byte for byte as it was.
    # Three in this file and always were: the pending note, the row failure ⓘ, and the title
    # one. Only the last is this script's business, and the next check is the one that pins it.
    ("imageVector = GetoIcons.Info,", 3, "no Info glyph gained or lost"),
    ("modifier = Modifier.size(18.dp),\n                            imageVector", 1,
     "and so is its size"),
    (".padding(start = 10.dp, top = 10.dp, bottom = 10.dp),", 1, "the row has no end padding"),
    # Untouched by design.
    ("ManagerSize.Compact ->", 7, "seven things still step with the tier, where there were eight"),
    ("ManagerSize.Roomy ->", 7, "and each still names all three arms"),
    ("MANAGER_MAX_WIDTH = 340.dp", 1, "no width changed"),
    ("MANAGER_ROOMY_WIDTH = 376.dp", 1, "on any tier"),
]


def main() -> int:
    path = ROOT / DIALOG

    if not path.is_file():
        print(f"REFUSED: missing {DIALOG}")
        return 1

    original = path.read_text(encoding="utf-8")

    text = original

    for old, new in EDITS:
        found = text.count(old)

        if found != 1:
            print(
                f"REFUSED: anchor {old.strip()[:70]!r}\n"
                f"  matched {found} time(s), expected exactly 1",
            )
            return 1

        if new and new in original:
            print("REFUSED: already applied — has this run before?")
            return 1

        text = text.replace(old, new, 1)

    for token, want, why in CHECKS:
        got = text.count(token)

        if got != want:
            print(f"REFUSED: {why} — {token[:44]!r} appears {got} time(s), expected {want}")
            return 1

        print(f"  checked  x{got:<3} {token[:52]!r}")

    def over(source: str) -> set[str]:
        return {
            line
            for line in source.split("\n")
            if len(line) > 120 and not line.lstrip().startswith("import ")
        }

    added = over(text) - over(original)

    if added:
        print(f"REFUSED: would gain lines over 120 chars: {sorted(added)}")
        return 1

    path.write_text(text, encoding="utf-8")

    print("\n  ok  the gear is hollow, 48 dp and tinted; the ⓘ sits over the switches")

    return 0


if __name__ == "__main__":
    sys.exit(main())
