#!/usr/bin/env python3
"""r4c — the struck-out eye, copied into `design-system` as the hide half of the new button.

The settings manager's action button becomes a hide/unhide pair at the author's instruction, and
the author chose his own tile pair for the two glyphs rather than new artwork:

    will unhide  ->  ic_hide_glyph    the open eye, already there since r2e
    will hide    ->  ic_hidden_glyph  the struck-out eye, written by this script

Both say **what the press gets you** rather than what it does, which is the same reading
`_v3_fav_hide_glyph.py` settled on for the first of them. Pressing a button that shows a
struck-out eye leaves your settings hidden; pressing the open eye leaves them visible.

⚠ **A copy rather than the original moved here**, for the reason r2e recorded: `:app`'s
`HideTileService` resolves `ic_hidden_tile` through its own `R`, and AGP 8 defaults
`android.nonTransitiveRClass` to true, so `:app`'s `R` does not carry a library module's
resources. Moving it would compile in the manifest and fail in Kotlin. Generating the copy is
what stops the two shapes drifting.

⚠ **The tile's fillColor is `@android:color/white` where its sibling's is `#FFFFFFFF`.** The
copy is written with the literal, matching `ic_hide_glyph` and the two glyphs beside it, so all
four files in `design-system/drawable` say the same thing the same way. Compose's `Icon` tints
over it either way; the difference is only whether a reader has to check.

Asserts the source is the single even-odd knockout it expects, and refuses rather than writing
something it cannot identify.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "app/src/main/res/drawable/ic_hidden_tile.xml"
TARGET = ROOT / "design-system/src/main/res/drawable/ic_hidden_glyph.xml"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  ~   GENERATED by design/_v3_hidden_glyph.py from app's ic_hidden_tile.xml. Do not edit by
  ~   hand; re-run the script.
  ~
  ~   The Hide settings tile's struck-out eye - the state it shows while settings are hidden -
  ~   reused as the hide half of the settings manager's hide/unhide button, at the author's
  ~   instruction. Like its sibling ic_hide_glyph it names what the press achieves rather than
  ~   what it does: press this and your settings end up hidden.
  ~
  ~   A copy rather than the original moved here, because :app's HideTileService resolves it
  ~   through its own R and a non-transitive R class would not carry a library's resources.
  ~
  ~   Carries no android:tint. Compose's Icon applies its own, and a tint here would fight it.
  -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:fillType="evenOdd"
        android:pathData="{path}" />
</vector>
"""


def main() -> int:
    problems: list[str] = []

    if not SOURCE.exists():
        print("REFUSED, nothing written")
        print(f"  {SOURCE} is missing")

        return 1

    source = SOURCE.read_text(encoding="utf-8")

    paths = re.findall(r'android:pathData="([^"]+)"', source)

    if len(paths) != 1:
        problems.append(f"expected 1 path in the tile, found {len(paths)}")

    if source.count('android:fillType="evenOdd"') != 1:
        problems.append("the tile is no longer a single even-odd knockout")

    if 'android:viewportWidth="24"' not in source:
        problems.append("the tile is no longer drawn on a 24 viewport")

    # The attribute, not the word: the tile's own comment says "No android:tint here on
    # purpose", and a bare substring test reads that as the thing it is warning against.
    if 'android:tint="' in source:
        problems.append("the tile has gained an android:tint, which must not be copied")

    if problems:
        print("REFUSED, nothing written")

        for problem in problems:
            print(f"  {problem}")

        return 1

    path = paths[0]

    # Four subpaths, one more than the open eye: the gear, the halo dilated out of the strike,
    # the eye with that halo cut from it, and the strike bar added back inside. The halo is what
    # gives a dark bar on a dark eye its margin of gear colour - build_hide_tiles.py explains
    # the geometry. Asserted so a redrawn tile cannot land here silently.
    subpaths = path.count("M")

    if subpaths != 4:
        print("REFUSED, nothing written")
        print(f"  expected 4 subpaths (gear, halo, eye, strike), found {subpaths}")

        return 1

    TARGET.write_text(HEADER.replace("{path}", path), encoding="utf-8")

    print(f"ok - wrote {TARGET.relative_to(ROOT)} ({len(path)} chars, {subpaths} subpaths)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
