#!/usr/bin/env python3
"""
v3-r2 — the monochrome IMD glyph for the settings manager's new button.

Two drawables rather than one, and that is what makes it dual-tone: a vector drawable's
fillColor is baked in, so a single file can only ever be tinted as a whole. Split into the gear
and the glyph inside it, the two can be stacked as two Icons with different tints and follow
the theme — which is what "looking like the i button" requires, since the ⓘ is themed too.

Paths are lifted verbatim from `ic_imd_app.xml`, so the shape cannot drift from the app icon.
The colours in that file are dropped; these carry none, and are tinted at draw time.

Asserts the source still has the four paths it expects and that the geometry it copies is the
gear — refuses rather than writing a shape it cannot identify.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design-system/src/main/res/drawable/ic_imd_app.xml"
OUT = ROOT / "design-system/src/main/res/drawable"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  ~   Unless required by applicable law or agreed to in writing, software
  ~   distributed under the License is distributed on an "AS IS" BASIS,
  ~   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~   See the License for the specific language governing permissions and
  ~   limitations under the License.
  ~
  ~   GENERATED by design/_v3_manager_logo.py from ic_imd_app.xml. Do not edit by hand;
  ~   re-run the script.
  ~
  ~   Carries no colour and no android:tint. Both are drawn through Compose's Icon, which
  ~   applies its own tint, and a tint here would fight it — and ?attr/colorControlNormal in
  ~   particular is an AppCompat attribute this module does not pull in, which aapt refuses.
  -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
"""

FOOTER = "</vector>\n"


def path_element(data: str) -> str:
    return f'    <path\n        android:fillColor="#FFFFFFFF"\n        android:pathData="{data}" />\n'


def main() -> int:
    if not SOURCE.exists():
        print("REFUSED, nothing written")
        print(f"  {SOURCE} is missing")

        return 1

    source = SOURCE.read_text(encoding="utf-8")

    paths = re.findall(
        r'android:fillColor="(#[0-9A-Fa-f]+)"\s*android:pathData="([^"]+)"',
        source,
    )

    problems: list[str] = []

    if len(paths) != 4:
        problems.append(f"expected 4 paths in the app icon, found {len(paths)}")

    else:
        colours = [colour.upper() for colour, _ in paths]

        if colours != ["#FFFFFF", "#A5DBB9", "#13A75B", "#A5DBB9"]:
            problems.append(f"unexpected path colours {colours}")

    if problems:
        print("REFUSED, nothing written")

        for problem in problems:
            print(f"  {problem}")

        return 1

    gear = paths[1][1]
    glyph = paths[2][1]
    pill = paths[3][1]

    # The gear is the one whose bounds are centred on 54,54 and span most of the canvas. If
    # that stops being true the icon has been redrawn and this script must be looked at, not
    # trusted.
    numbers = [float(n) for n in re.findall(r"-?\d+\.?\d*", gear)]
    xs, ys = numbers[0::2], numbers[1::2]

    centre_x = (min(xs) + max(xs)) / 2
    centre_y = (min(ys) + max(ys)) / 2

    if abs(centre_x - 54) > 1 or abs(centre_y - 54) > 1:
        print("REFUSED, nothing written")
        print(f"  the gear path is not centred on 54,54 (got {centre_x:.1f},{centre_y:.1f})")

        return 1

    written = {
        OUT / "ic_imd_glyph_gear.xml": HEADER + path_element(gear) + FOOTER,
        OUT / "ic_imd_glyph_inner.xml": HEADER + path_element(glyph) + path_element(pill) + FOOTER,
    }

    for path, text in written.items():
        path.write_text(text, encoding="utf-8")
        print(f"  wrote {path.relative_to(ROOT)}")

    print(f"ok — {len(written)} monochrome drawables, gear radius {(max(xs) - min(xs)) / 2:.2f}/108")

    return 0


if __name__ == "__main__":
    sys.exit(main())
