#!/usr/bin/env python3
"""
v3-r2e — the Favourites FAB's new icon: the Hide settings tile's open eye.

The author's instruction: "in fav tab update the revert(now restore) button icon with of hide
settings QS toggle showed when settings are visible" — that is `ic_hide_tile`, the state the
tile shows while nothing is hidden. It reads as the **outcome** of pressing the button rather
than its mechanism, which is what a FAB should say: press this and your settings are visible
again.

⚠ **Copied into `design-system`, not moved there.** The drawable lives in `:app` and the FAB
lives in `:feature:apps`, which cannot see it. Moving it would break `HideTileService`'s
`R.drawable.ic_hide_tile`: AGP 8 defaults `android.nonTransitiveRClass` to true, so the app's R
does **not** carry a library module's resources — the manifest's `@drawable/` reference would
still resolve through resource merging, and the Kotlin one would not compile. A copy generated
from the original is the cheap half of that trade: the shape cannot drift, because this script
re-derives it.

The three glyphs it will sit beside — `ic_services_glyph`, `ic_revert_glyph` and the tile
itself — are structurally identical: one even-odd path, white, 24 viewport, no `android:tint`.
Compose's `Icon` tints the whole thing, which is what makes a knockout work as a FAB glyph.

Asserts the source is the single-path even-odd shape it expects, and refuses rather than
writing something it cannot identify.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "app/src/main/res/drawable/ic_hide_tile.xml"
TARGET = ROOT / "design-system/src/main/res/drawable/ic_hide_glyph.xml"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  ~   GENERATED by design/_v3_fav_hide_glyph.py from app's ic_hide_tile.xml. Do not edit by
  ~   hand; re-run the script.
  ~
  ~   The Hide settings tile's open eye — the state it shows while nothing is hidden — reused
  ~   as the Favourites tab's unhide button, at the author's instruction. It says what the
  ~   press achieves rather than what it does.
  ~
  ~   A copy rather than the original moved here, because :app's HideTileService resolves it
  ~   through its own R and a non-transitive R class would not carry a library's resources.
  ~
  ~   Carries no android:tint. Compose's Icon applies its own, and a tint here would fight it.
  -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:fillType="evenOdd"
        android:pathData="{path}" />
</vector>
"""


def main() -> int:
    problems: list[str] = []

    if not SOURCE.exists():
        print("REFUSED, nothing written")
        print(f"  {SOURCE} is missing")

        return 1

    source = SOURCE.read_text(encoding="utf-8")

    paths = re.findall(r'android:pathData="([^"]+)"', source)

    if len(paths) != 1:
        problems.append(f"expected 1 path in the tile, found {len(paths)}")

    if source.count('android:fillType="evenOdd"') != 1:
        problems.append("the tile is no longer a single even-odd knockout")

    if 'android:viewportWidth="24"' not in source:
        problems.append("the tile is no longer drawn on a 24 viewport")

    # The attribute, not the word: the tile's own comment says "No android:tint here on
    # purpose", and a bare substring test reads that as the thing it is warning against.
    if 'android:tint="' in source:
        problems.append("the tile has gained an android:tint, which must not be copied")

    if problems:
        print("REFUSED, nothing written")

        for problem in problems:
            print(f"  {problem}")

        return 1

    path = paths[0]

    # Three subpaths: the gear, the eye punched out of it, and the pupil punched out of that,
    # which even-odd renders solid again. Asserted so a redrawn tile cannot land here silently.
    subpaths = path.count("M")

    if subpaths != 3:
        print("REFUSED, nothing written")
        print(f"  expected 3 subpaths (gear, eye, pupil), found {subpaths}")

        return 1

    TARGET.write_text(HEADER.replace("{path}", path), encoding="utf-8")

    print(f"ok — wrote {TARGET.relative_to(ROOT)} ({len(path)} chars, {subpaths} subpaths)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
