#!/usr/bin/env python3
"""The launcher icon as a drawable feature modules can reach.

The manager dialog wants the app's own icon beside its title, and it lives in
`feature/apps`, which cannot see the `app` module's mipmaps — module resources only
travel the other way. Rather than hand-copy the artwork and let the two drift, this
reads the real `ic_launcher_foreground.xml` and re-emits it into `design-system`
with the plate the launcher draws underneath it.

Idempotent: the source vector is read, never written.
"""
import math
import pathlib
import re
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"
OUT = ROOT / "design-system/src/main/res/drawable/ic_imd_app.xml"

ANDROID = "http://schemas.android.com/apk/res/android"

# The adaptive mask shows the middle 72 of the 108 viewport. The plate is drawn at that
# size so the icon in the dialog is the icon on the homescreen, at the same crop.
VISIBLE = 72.0
CENTRE = 54.0

# n=4.6 superellipse. Android's own mask is a squircle rather than a rounded rectangle,
# and at this size the difference between the two is visible as a flat spot in the corner.
SQUIRCLE_N = 4.6
STEPS = 96

LICENCE = """<!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  ~   GENERATED by design/build_app_glyph.py from app/.../ic_launcher_foreground.xml
  ~   and the ic_launcher_background colour. Do not edit by hand; re-run the script.
  -->"""


def squircle_path() -> str:
    r = VISIBLE / 2
    pts = []

    for i in range(STEPS):
        t = 2 * math.pi * i / STEPS
        ct, st = math.cos(t), math.sin(t)
        x = CENTRE + r * math.copysign(abs(ct) ** (2 / SQUIRCLE_N), ct)
        y = CENTRE + r * math.copysign(abs(st) ** (2 / SQUIRCLE_N), st)
        pts.append(f"{x:.2f},{y:.2f}")

    return "M" + "L".join(pts) + "Z"


def main() -> None:
    background = re.search(
        r'name="ic_launcher_background">([^<]+)<',
        (RES / "values/colors.xml").read_text(),
    ).group(1)

    root = ET.parse(RES / "drawable/ic_launcher_foreground.xml").getroot()

    paths = [
        f'    <path\n'
        f'        android:fillColor="{p.get(f"{{{ANDROID}}}fillColor") or "#000000"}"\n'
        f'        android:pathData="{p.get(f"{{{ANDROID}}}pathData")}" />'
        for p in root.iter("path")
        if p.get(f"{{{ANDROID}}}pathData")
    ]

    assert paths, "no paths in ic_launcher_foreground.xml"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"{LICENCE}\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        f'    <path\n'
        f'        android:fillColor="{background}"\n'
        f'        android:pathData="{squircle_path()}" />\n'
        + "\n".join(paths)
        + "\n</vector>\n",
    )

    print(f"{OUT.relative_to(ROOT)}  <- plate {background}, {len(paths)} artwork paths")


if __name__ == "__main__":
    main()
