#!/usr/bin/env python3
"""The coloured 'settings hidden' artwork for the Revert to default notification.

The notification used the app's own logo, which said "IMD" and nothing else. What the
notification is actually about is that settings are hidden right now — which is exactly what
the Hide settings tile's "on" glyph says — so it now carries that glyph instead, in the same
two greens as the other coloured IMD icons.

**Nothing here is redrawn.** The gear is lifted verbatim from the drawable this replaces, and
the struck eye is built by calling the tile generator's own geometry and then scaling it into
the larger canvas. Both halves therefore stay in step with what ships: change the tile and
re-run this, and the notification follows.

The one real difference is what the glyph *is*. On a tile it is a hole punched in the gear,
because a tile icon is a single colour; here it is a second colour on top, so the same regions
are filled green instead of cut away. Even-odd still does the nesting: the pupil and the gap
either side of the strike are rings inside the eye, and they come out gear-coloured without
being drawn twice.

**Run this after build_revert.py, never before.** That script writes the same file with a
revert arrow in it, so running them the other way round quietly undoes this one.

Needs shapely and svgpathtools. None of this runs during the Android build.
"""
import math
import pathlib
import re
import sys

from shapely import affinity
from shapely.ops import unary_union
from svgpathtools import parse_path

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from build_hide_tiles import (  # noqa: E402
    CENTRE as TILE_CENTRE,
    GEAR_VALLEY_R as TILE_VALLEY_R,
    from_reference,
    lens,
    paths_of,
    rings_of,
    slash,
)

REPO = pathlib.Path(__file__).resolve().parent.parent
TARGET = REPO / 'framework/notification-manager/src/main/res/drawable/ic_revert_notification_large.xml'

MINT, GREEN = '#A5DBB9', '#13A75B'
CENTRE = (54.0, 54.0)

# The same clearance rule the tile uses, as a fraction of the valley radius rather than an
# absolute, so it means the same thing in a canvas 4.5x larger.
MARGIN_RATIO = 0.85 / TILE_VALLEY_R

LICENCE = '''<?xml version="1.0" encoding="utf-8"?><!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  -->
'''

NOTE = '''<!--
  The large icon on the "Revert to default" notification: the app's gear with the Hide
  settings tile's "settings hidden" glyph inside it, in the coloured pair the other IMD
  icons use.

  Generated by design/build_hidden_notification.py, which lifts the gear from whatever this
  file already held and builds the glyph by calling the tile generator - so the notification
  and the tile cannot drift apart. Edit that script, not this file.
-->
'''


def gear_path():
    """The gear this drawable already carries, taken verbatim."""
    paths = re.findall(r'android:pathData="([^"]+)"', TARGET.read_text())

    if not paths:
        raise SystemExit(f'no pathData in {TARGET}')

    return paths[0].strip()


def valley_radius(path_data, steps=400):
    """How close the gear's rim comes to the centre, which is what caps the glyph.

    Measured rather than assumed: the rim is a wave, and it is the valleys between the teeth
    that decide how much room there is - the same reasoning, and the same number, that the
    tile generator works from at its own scale.
    """
    p = parse_path(path_data)

    return min(
        math.hypot(z.real - CENTRE[0], z.imag - CENTRE[1])
        for seg in p
        for z in (seg.point(i / steps) for i in range(steps + 1))
    )


def hidden_glyph(scale):
    """The tile's 'on' geometry, scaled up and moved to this canvas's centre."""
    v = from_reference(6.60)

    eye = lens(v['half_w'], v['half_h'], v['round_by'])
    pupil = __import__('shapely.geometry', fromlist=['Point']).Point(TILE_CENTRE).buffer(
        v['pupil_r'], quad_segs=96,
    )
    strike = slash(v['slash_w'], v['slash_len'], v['slash_deg'])
    halo = strike.buffer(v['gap'], quad_segs=48)

    glyph = unary_union([eye.difference(halo).difference(pupil), strike])

    glyph = affinity.scale(glyph, xfact=scale, yfact=scale, origin=TILE_CENTRE)

    return affinity.translate(
        glyph,
        xoff=CENTRE[0] - TILE_CENTRE[0],
        yoff=CENTRE[1] - TILE_CENTRE[1],
    )


def main():
    gear = gear_path()

    valley = valley_radius(gear)

    scale = valley / TILE_VALLEY_R

    glyph = hidden_glyph(scale)

    reach = max(
        math.hypot(x - CENTRE[0], y - CENTRE[1])
        for ring in rings_of(glyph)
        for x, y in ring
    )

    room = valley - reach

    assert room >= valley * MARGIN_RATIO, (
        f'only {room:.2f} of clearance inside a valley of {valley:.2f}, '
        f'needs {valley * MARGIN_RATIO:.2f}'
    )

    body = (
        f'{LICENCE}{NOTE}'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        '    <path\n'
        f'        android:fillColor="{MINT}"\n'
        f'        android:pathData="{gear}" />\n'
        '    <path\n'
        f'        android:fillColor="{GREEN}"\n'
        '        android:fillType="evenOdd"\n'
        f'        android:pathData="{" ".join(paths_of(glyph))}" />\n'
        '</vector>\n'
    )

    TARGET.write_text(body)

    print(f'{TARGET.name}: valley {valley:.2f}, glyph reach {reach:.2f}, '
          f'{room:.2f} clear (needs {valley * MARGIN_RATIO:.2f}), scale x{scale:.3f}')


if __name__ == '__main__':
    main()
