#!/usr/bin/env python3
"""
The failure notification's icon: the same gear, with a bold exclamation mark where the revert
arrow was.

The gear is lifted verbatim from `ic_revert_notification_small.xml` rather than redrawn, for
the reason the tile and the hidden-notification glyph share one generator: two hand-kept copies
of the same shape drift, and a status-bar icon that is *almost* the app's gear reads as a
different app's icon rather than as this one's. Only the glyph inside it changes.

How the file works. One path, `evenOdd`: the first sub-path is the gear's outline and every
sub-path after it is a hole punched through it. So swapping the glyph is swapping everything
after the first `Z` — nothing about the gear needs to be understood, only where it ends.

Geometry of the mark, in the 24-unit viewport the gear is drawn in:

    stem   x 10.5 - 13.5, fully rounded caps (r = 1.5), spanning y 6.5 - 13.5
    dot    centre (12.0, 16.0), r = 1.6, spanning y 14.4 - 17.6

Both sit inside the gear's inner opening, which the revert glyph measures out as roughly a
circle of radius 6 about (12, 12). The stem is three units wide against a two-unit arrow: at
status-bar size the system draws this monochrome and small, and a mark that is merely correct
disappears at 24 dp.
"""

import os
import re
import sys

ROOT = os.environ.get(
    "GETO_ROOT",
    os.path.abspath(os.path.join(os.path.dirname(__file__), "..")),
)

DRAWABLE = os.path.join(
    ROOT, "framework", "notification-manager", "src", "main", "res", "drawable"
)

SOURCE = os.path.join(DRAWABLE, "ic_revert_notification_small.xml")
TARGET = os.path.join(DRAWABLE, "ic_failure_notification_small.xml")

# --- the mark -------------------------------------------------------------

STEM_HALF_WIDTH = 1.5
STEM_CENTRE_X = 12.0
STEM_TOP = 6.5
STEM_BOTTOM = 13.5

DOT_CENTRE_X = 12.0
DOT_CENTRE_Y = 16.0
DOT_RADIUS = 1.6


def stem_path():
    """A capsule: two vertical sides closed by semicircular caps."""
    left = STEM_CENTRE_X - STEM_HALF_WIDTH
    right = STEM_CENTRE_X + STEM_HALF_WIDTH

    # Where the straight sides start and end, i.e. inside the caps.
    top = STEM_TOP + STEM_HALF_WIDTH
    bottom = STEM_BOTTOM - STEM_HALF_WIDTH

    r = STEM_HALF_WIDTH

    # sweep = 1 is clockwise in a y-down space, so left-to-right bulges up over the top and
    # right-to-left bulges down under the bottom.
    return (
        f"M{left:.3f},{bottom:.3f}"
        f"L{left:.3f},{top:.3f}"
        f"A{r:.3f},{r:.3f} 0 0 1 {right:.3f},{top:.3f}"
        f"L{right:.3f},{bottom:.3f}"
        f"A{r:.3f},{r:.3f} 0 0 1 {left:.3f},{bottom:.3f}Z"
    )


def dot_path():
    """A circle, as the two semicircles every path parser agrees on."""
    left = DOT_CENTRE_X - DOT_RADIUS
    right = DOT_CENTRE_X + DOT_RADIUS
    y = DOT_CENTRE_Y
    r = DOT_RADIUS

    return (
        f"M{left:.3f},{y:.3f}"
        f"A{r:.3f},{r:.3f} 0 0 1 {right:.3f},{y:.3f}"
        f"A{r:.3f},{r:.3f} 0 0 1 {left:.3f},{y:.3f}Z"
    )


HEADER = """<?xml version="1.0" encoding="utf-8"?><!--
  ~
  ~   Copyright 2026 soul_99 (suIMD)
  ~
  ~   Licensed under the GNU General Public License v3.0 (the "License");
  ~   you may not use this file except in compliance with the License.
  ~   You may obtain a copy of the License at
  ~
  ~       https://www.gnu.org/licenses/gpl-3.0
  ~
  ~   Generated by design/build_failure_notification.py - do not edit by hand.
  ~
  -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <!--
      The revert notification's gear, with a bold exclamation mark in place of its arrow.
      A status-bar icon is drawn as a single-colour silhouette and tinted by the system, so
      the glyph is a hole through the gear rather than a second colour.
    -->
    <path
        android:fillColor="@android:color/white"
        android:fillType="evenOdd"
        android:pathData="%s" />
</vector>
"""


def main():
    print("ROOT = %s" % ROOT)

    if not os.path.exists(SOURCE):
        print("REFUSED: %s not found" % SOURCE)

        return 1

    source = open(SOURCE, encoding="utf-8").read()

    match = re.search(r'android:pathData="([^"]+)"', source)

    if match is None:
        print("REFUSED: no pathData in the revert icon")

        return 1

    data = match.group(1)

    # The gear is everything up to and including the first close. Asserted rather than
    # assumed: if the revert icon is ever regenerated as several sub-paths for the gear
    # itself, this would silently take a fragment of it and draw a broken shape.
    end = data.find("Z")

    if end == -1:
        print("REFUSED: the revert path has no closed sub-path")

        return 1

    gear = data[: end + 1]

    if gear.count("M") != 1:
        print("REFUSED: expected one move-to in the gear outline, found %d" % gear.count("M"))

        return 1

    if len(data) - len(gear) < 100:
        print("REFUSED: nothing recognisable follows the gear - is this the right file?")

        return 1

    combined = gear + stem_path() + dot_path()

    open(TARGET, "w", encoding="utf-8").write(HEADER % combined)

    print("  gear outline: %d chars, lifted verbatim" % len(gear))
    print("  stem:  x %.1f-%.1f, y %.1f-%.1f" % (
        STEM_CENTRE_X - STEM_HALF_WIDTH,
        STEM_CENTRE_X + STEM_HALF_WIDTH,
        STEM_TOP,
        STEM_BOTTOM,
    ))
    print("  dot:   centre (%.1f, %.1f), r %.1f" % (DOT_CENTRE_X, DOT_CENTRE_Y, DOT_RADIUS))
    print("\nwrote %s" % os.path.relpath(TARGET, ROOT))

    return 0


if __name__ == "__main__":
    sys.exit(main())
